import type { FeedItem } from '../services/marketplace.service';

export const SEED_FEED: FeedItem[] = [
  // ── POST ──────────────────────────────────────────────────────────────────
  {
    id: 'post-1',
    type: 'POST',
    authorId: 'u1',
    authorName: 'Rajesh Kumar',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    authorBio: 'MD @ Kumar Traders · Mumbai',
    content: {
      text: 'Excited to announce that we have expanded our distribution network to 3 new cities — Pune, Nashik & Aurangabad! 🎉 Connect with us for wholesale enquiries on industrial hardware.',
      images: [
        'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&q=80',
      ],
    },
    tags: ['expansion', 'hardware', 'wholesale'],
    likes: 142,
    comments: 23,
    saves: 8,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },

  // ── PRODUCT ───────────────────────────────────────────────────────────────
  {
    id: 'prod-1',
    type: 'PRODUCT',
    authorId: 'u2',
    authorName: 'Priya Electricals',
    authorAvatar: 'https://i.pravatar.cc/150?img=5',
    authorBio: 'Electrical Supplier · Hyderabad',
    content: {},
    likes: 89,
    comments: 14,
    saves: 31,
    isLiked: true,
    isSaved: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    listing: {
      id: 'lst-1',
      title: 'LED Panel Light 40W — Cool White',
      description: 'Premium quality LED panel lights suitable for offices, showrooms & retail outlets. ISI marked, 3-year warranty.',
      price: 850,
      mrp: 1200,
      images: [
        'https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=600&q=80',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
      ],
      sellerId: 'u2',
      sellerName: 'Priya Electricals',
      sellerAvatar: 'https://i.pravatar.cc/150?img=5',
      category: 'Electricals',
      unit: 'piece',
      minOrder: 10,
      stock: 480,
      tags: ['LED', 'lighting', 'commercial'],
      averageRating: 4.6,
      reviewCount: 38,
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
  },

  // ── OFFER ─────────────────────────────────────────────────────────────────
  {
    id: 'offer-1',
    type: 'OFFER',
    authorId: 'u3',
    authorName: 'ShopEasy Wholesale',
    authorAvatar: 'https://i.pravatar.cc/150?img=33',
    authorBio: 'B2B Marketplace · Pan India',
    content: {},
    likes: 210,
    comments: 45,
    saves: 67,
    isLiked: false,
    isSaved: true,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    offer: {
      id: 'off-1',
      title: 'Mega Monsoon Sale — Up to 30% Off',
      description: 'Valid on all bulk orders above ₹25,000. Limited period offer for registered buyers.',
      code: 'MONSOON30',
      discountType: 'PERCENTAGE',
      discountValue: 30,
      minOrderValue: 25000,
      maxDiscount: 15000,
      maxRedemptions: 500,
      currentRedemptions: 312,
      expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      terms: 'Valid on minimum order of ₹25,000. Cannot be combined with other offers. One redemption per business.',
    },
  },

  // ── LAUNCH ────────────────────────────────────────────────────────────────
  {
    id: 'launch-1',
    type: 'LAUNCH',
    authorId: 'u4',
    authorName: 'GreenTech Industries',
    authorAvatar: 'https://i.pravatar.cc/150?img=48',
    authorBio: 'Sustainable Manufacturing · Ahmedabad',
    content: {
      text: 'Introducing our new line of eco-friendly packaging solutions — 100% biodegradable, food-grade certified.',
    },
    tags: ['newlaunch', 'ecofriendly', 'packaging', 'sustainable'],
    likes: 375,
    comments: 62,
    saves: 94,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    listing: {
      id: 'lst-2',
      title: 'Biodegradable Packaging Boxes — Custom Sizes',
      description: 'Made from sugarcane bagasse and recycled kraft paper. Available in 50+ standard sizes with custom printing options. MOQ 500 pcs.',
      price: 12,
      mrp: 18,
      images: [
        'https://images.unsplash.com/photo-1609097524316-5a89bf67b0fc?w=600&q=80',
        'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&q=80',
        'https://images.unsplash.com/photo-1567958451986-2de427a4a0be?w=600&q=80',
      ],
      sellerId: 'u4',
      sellerName: 'GreenTech Industries',
      sellerAvatar: 'https://i.pravatar.cc/150?img=48',
      category: 'Packaging',
      unit: 'piece',
      minOrder: 500,
      stock: 12000,
      tags: ['biodegradable', 'eco', 'packaging'],
      createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    },
  },

  // ── FEEDBACK ──────────────────────────────────────────────────────────────
  {
    id: 'feedback-1',
    type: 'FEEDBACK',
    authorId: 'u5',
    authorName: 'Anita Sharma',
    authorAvatar: 'https://i.pravatar.cc/150?img=9',
    authorBio: 'Purchase Manager · Delhi NCR',
    content: {},
    likes: 56,
    comments: 7,
    saves: 3,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    review: {
      id: 'rev-1',
      listingId: 'lst-1',
      reviewerId: 'u5',
      reviewerName: 'Anita Sharma',
      reviewerAvatar: 'https://i.pravatar.cc/150?img=9',
      rating: 5,
      title: 'Excellent quality, delivered on time!',
      body: 'Ordered 200 LED panels for our new office fitout. Installation was seamless and the build quality is outstanding. The 3-year warranty gives great peace of mind. Highly recommend!',
      createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    },
    listing: {
      id: 'lst-1',
      title: 'LED Panel Light 40W — Cool White',
      price: 850,
      mrp: 1200,
      sellerId: 'u2',
      sellerName: 'Priya Electricals',
      category: 'Electricals',
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
  },

  // ── POST with multiple images ─────────────────────────────────────────────
  {
    id: 'post-2',
    type: 'POST',
    authorId: 'u6',
    authorName: 'Vikram Textiles',
    authorAvatar: 'https://i.pravatar.cc/150?img=22',
    authorBio: 'Fabric Exporter · Surat',
    content: {
      text: 'Just wrapped up the International Textile Expo 2026! Amazing response to our new viscose collection. Thank you to all our partners and buyers who visited our stall 🙏',
      images: [
        'https://images.unsplash.com/photo-1558171813-9b759ef5-a3ef?w=600&q=80',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
        'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&q=80',
        'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
      ],
    },
    tags: ['textile', 'expo', 'fabric', 'surat'],
    likes: 298,
    comments: 41,
    saves: 15,
    isLiked: true,
    isSaved: false,
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },

  // ── REQUIREMENT ───────────────────────────────────────────────────────────
  {
    id: 'req-1',
    type: 'REQUIREMENT',
    authorId: 'u7',
    authorName: 'Metro Construction',
    authorAvatar: 'https://i.pravatar.cc/150?img=57',
    authorBio: 'Infrastructure · Chennai',
    content: {},
    likes: 34,
    comments: 18,
    saves: 9,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    requirement: {
      id: 'r1',
      title: 'TMT Steel Bars — Fe-500D Grade',
      description: 'Looking for ISI certified TMT bars for a major infrastructure project. Delivery required at Tambaram site, Chennai. Rate contract for 6 months preferred.',
      category: 'Machinery',
      quantity: 500,
      budget: 2500000,
      authorId: 'u7',
      authorName: 'Metro Construction',
      status: 'OPEN',
      createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    },
  },

  // ── PRODUCT 2 ─────────────────────────────────────────────────────────────
  {
    id: 'prod-2',
    type: 'PRODUCT',
    authorId: 'u8',
    authorName: 'Spice Route Trading Co.',
    authorAvatar: 'https://i.pravatar.cc/150?img=41',
    authorBio: 'FMCG Distributor · Kochi',
    content: {},
    likes: 176,
    comments: 29,
    saves: 52,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    listing: {
      id: 'lst-3',
      title: 'Premium Turmeric Powder — Export Grade',
      description: 'Single-origin Lakadong turmeric from Meghalaya. High curcumin content (5.5%+). FSSAI certified. Available in 25kg, 50kg bags. Suitable for food processing & export.',
      price: 320,
      mrp: 420,
      images: [
        'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&q=80',
        'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80',
      ],
      sellerId: 'u8',
      sellerName: 'Spice Route Trading Co.',
      sellerAvatar: 'https://i.pravatar.cc/150?img=41',
      category: 'Food',
      unit: 'kg',
      minOrder: 25,
      stock: 8,
      tags: ['turmeric', 'spices', 'organic', 'export'],
      averageRating: 4.8,
      reviewCount: 72,
      createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    },
  },

  // ── OFFER 2 ───────────────────────────────────────────────────────────────
  {
    id: 'offer-2',
    type: 'OFFER',
    authorId: 'u9',
    authorName: 'TechParts India',
    authorAvatar: 'https://i.pravatar.cc/150?img=61',
    authorBio: 'Electronics Components · Bengaluru',
    content: {},
    likes: 88,
    comments: 11,
    saves: 40,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    offer: {
      id: 'off-2',
      title: 'First Order Flat ₹2000 Off',
      description: 'New buyer discount on your first bulk order. Valid for registered businesses only.',
      code: 'FIRST2000',
      discountType: 'FLAT',
      discountValue: 2000,
      minOrderValue: 10000,
      maxRedemptions: 200,
      currentRedemptions: 87,
      expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      terms: 'One per business. Valid on first order only. Min order ₹10,000.',
    },
  },
];
