-- CreateEnum
CREATE TYPE "ScheduledEventType" AS ENUM ('MEETING', 'CALL', 'FOLLOW_UP', 'VISIT', 'TRAINING', 'WEBINAR', 'BREAK', 'PERSONAL', 'HOLIDAY', 'OTHER');
CREATE TYPE "EventStatus" AS ENUM ('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'NO_SHOW');
CREATE TYPE "RSVPStatus" AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'TENTATIVE');
CREATE TYPE "CalendarSourceType" AS ENUM ('TASK', 'ACTIVITY', 'DEMO', 'TOUR_PLAN', 'REMINDER', 'FOLLOW_UP', 'SCHEDULED_EVENT', 'EXTERNAL_GOOGLE', 'EXTERNAL_OUTLOOK');
CREATE TYPE "CalendarSyncProvider" AS ENUM ('GOOGLE', 'OUTLOOK', 'ICAL');
CREATE TYPE "CalendarSyncDirection" AS ENUM ('ONE_WAY_TO_CRM', 'ONE_WAY_FROM_CRM', 'TWO_WAY');
CREATE TYPE "CalendarSyncStatus" AS ENUM ('ACTIVE', 'PAUSED', 'ERROR', 'DISCONNECTED');
CREATE TYPE "AvailabilityStatus" AS ENUM ('FREE', 'BUSY', 'TENTATIVE', 'OUT_OF_OFFICE');
CREATE TYPE "TaskStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD', 'OVERDUE');
CREATE TYPE "TaskPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT', 'CRITICAL');
CREATE TYPE "TaskType" AS ENUM ('GENERAL', 'FOLLOW_UP', 'REMINDER', 'ACTIVITY_LINKED', 'APPROVAL', 'REVIEW', 'CALL_BACK', 'MEETING', 'DEMO', 'CUSTOM');
CREATE TYPE "TaskRecurrence" AS ENUM ('NONE', 'DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY');
CREATE TYPE "TaskAssignmentScope" AS ENUM ('SELF', 'REPORTEES', 'ANY_USER', 'SPECIFIC_USER', 'DEPARTMENT', 'DESIGNATION', 'ROLE');
CREATE TYPE "ReminderStatus" AS ENUM ('PENDING', 'SENT', 'TRIGGERED', 'ACKNOWLEDGED', 'SNOOZED', 'MISSED', 'DISMISSED', 'CANCELLED');
CREATE TYPE "ReminderType" AS ENUM ('PERSONAL', 'TASK_LINKED', 'ACTIVITY_LINKED', 'FOLLOW_UP_LINKED', 'SYSTEM', 'ONCE', 'RECURRING');
CREATE TYPE "CommentVisibility" AS ENUM ('PUBLIC', 'PRIVATE');
CREATE TYPE "CommentEntityType" AS ENUM ('LEAD', 'CONTACT', 'ORGANIZATION', 'TASK', 'ACTIVITY', 'QUOTATION', 'TICKET', 'INVOICE', 'DEMO');
CREATE TYPE "NotificationEventType" AS ENUM ('TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_COMPLETED', 'TASK_OVERDUE', 'TASK_COMMENT', 'TASK_COMMENT_ADDED', 'REMINDER_DUE', 'REMINDER_TRIGGERED', 'REMINDER_MISSED', 'LEAD_ASSIGNED', 'LEAD_STATUS_CHANGED', 'LEAD_COMMENT_ADDED', 'LEAD_FOLLOW_UP_DUE', 'LEAD_WON', 'LEAD_LOST', 'ACTIVITY_TAGGED', 'ACTIVITY_REMINDER', 'COMMENT_ADDED', 'COMMENT_PRIVATE', 'APPROVAL_REQUIRED', 'ESCALATION_TRIGGERED', 'SYSTEM_ALERT', 'CUSTOM');
CREATE TYPE "EscalationAction" AS ENUM ('NOTIFY_MANAGER', 'NOTIFY_ADMIN', 'REASSIGN', 'REASSIGN_TASK', 'ESCALATE_UP', 'CHANGE_PRIORITY', 'AUTO_CLOSE', 'CUSTOM_WEBHOOK');

-- AlterEnum - extend existing enums
ALTER TYPE "NotificationChannel" ADD VALUE 'CALL';
ALTER TYPE "RecurrencePattern" ADD VALUE 'NONE';
ALTER TYPE "RecurrencePattern" ADD VALUE 'WEEKDAYS';
ALTER TYPE "RecurrencePattern" ADD VALUE 'BIWEEKLY';
ALTER TYPE "RecurrencePattern" ADD VALUE 'MONTHLY_NTH';
ALTER TYPE "RecurrencePattern" ADD VALUE 'QUARTERLY';
ALTER TYPE "RecurrencePattern" ADD VALUE 'YEARLY';
ALTER TYPE "RecurrencePattern" ADD VALUE 'CUSTOM';
