import { PrismaClient } from '@prisma/client';

/**
 * Seed data for ErrorCatalog — 45+ error codes with English + Hindi messages.
 * Run: npx prisma db seed  (or call seedErrorCatalog(prisma) directly)
 */

interface ErrorSeedEntry {
  code: string;
  layer: 'BE' | 'FE' | 'DB' | 'MOB';
  module: string;
  severity: 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';
  httpStatus: number;
  messageEn: string;
  messageHi: string;
  solutionEn: string;
  solutionHi: string;
  helpUrl?: string;
  isRetryable?: boolean;
  retryAfterMs?: number;
}

export const ERROR_CATALOG_SEED: ErrorSeedEntry[] = [
  // ═══════════════════════════════════════════════════
  // GENERIC (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'INTERNAL_ERROR',
    layer: 'BE',
    module: 'SYSTEM',
    severity: 'CRITICAL',
    httpStatus: 500,
    messageEn: 'An unexpected internal error occurred',
    messageHi: 'एक अप्रत्याशित आंतरिक त्रुटि हुई',
    solutionEn: 'Contact support with the traceId from the error response.',
    solutionHi: 'त्रुटि प्रतिक्रिया से traceId के साथ सहायता से संपर्क करें।',
  },
  {
    code: 'VALIDATION_ERROR',
    layer: 'BE',
    module: 'SYSTEM',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'One or more fields have invalid values',
    messageHi: 'एक या अधिक फ़ील्ड में अमान्य मान हैं',
    solutionEn: 'Check the details array for field-level errors and fix each one.',
    solutionHi: 'फ़ील्ड-स्तरीय त्रुटियों के लिए विवरण सरणी जांचें और प्रत्येक को ठीक करें।',
  },
  {
    code: 'NOT_FOUND',
    layer: 'BE',
    module: 'SYSTEM',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'The requested resource was not found',
    messageHi: 'अनुरोधित संसाधन नहीं मिला',
    solutionEn: 'Verify the resource ID exists. Use the list endpoint to check.',
    solutionHi: 'सत्यापित करें कि संसाधन ID मौजूद है। जांच के लिए सूची एंडपॉइंट का उपयोग करें।',
  },
  {
    code: 'DUPLICATE_ENTRY',
    layer: 'DB',
    module: 'SYSTEM',
    severity: 'WARNING',
    httpStatus: 409,
    messageEn: 'A record with the same unique value already exists',
    messageHi: 'समान अद्वितीय मान वाला एक रिकॉर्ड पहले से मौजूद है',
    solutionEn: 'Check for existing records with the same email, phone, or unique identifier.',
    solutionHi: 'समान ईमेल, फ़ोन, या अद्वितीय पहचानकर्ता वाले मौजूदा रिकॉर्ड की जांच करें।',
  },
  {
    code: 'INVALID_INPUT',
    layer: 'BE',
    module: 'SYSTEM',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'The provided input is not valid',
    messageHi: 'प्रदान किया गया इनपुट मान्य नहीं है',
    solutionEn: 'Review the request body and ensure all required fields are correct.',
    solutionHi: 'अनुरोध बॉडी की समीक्षा करें और सुनिश्चित करें कि सभी आवश्यक फ़ील्ड सही हैं।',
  },
  {
    code: 'OPERATION_FAILED',
    layer: 'BE',
    module: 'SYSTEM',
    severity: 'ERROR',
    httpStatus: 500,
    messageEn: 'The operation could not be completed',
    messageHi: 'ऑपरेशन पूरा नहीं हो सका',
    solutionEn: 'Retry the request. If the problem persists, contact support.',
    solutionHi: 'अनुरोध पुनः प्रयास करें। यदि समस्या बनी रहती है, तो सहायता से संपर्क करें।',
  },
  {
    code: 'RATE_LIMIT_EXCEEDED',
    layer: 'BE',
    module: 'SYSTEM',
    severity: 'WARNING',
    httpStatus: 429,
    messageEn: 'Too many requests. Rate limit exceeded.',
    messageHi: 'बहुत अधिक अनुरोध। दर सीमा पार हो गई।',
    solutionEn: 'Wait before making more requests. Check rate limit headers.',
    solutionHi: 'अधिक अनुरोध करने से पहले प्रतीक्षा करें। दर सीमा हेडर जांचें।',
  },
  {
    code: 'SERVICE_UNAVAILABLE',
    layer: 'BE',
    module: 'SYSTEM',
    severity: 'CRITICAL',
    httpStatus: 503,
    messageEn: 'The service is temporarily unavailable',
    messageHi: 'सेवा अस्थायी रूप से अनुपलब्ध है',
    solutionEn: 'Try again in a few minutes.',
    solutionHi: 'कुछ मिनटों में पुनः प्रयास करें।',
  },

  // ═══════════════════════════════════════════════════
  // AUTH & ACCESS (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'AUTH_TOKEN_MISSING',
    layer: 'BE',
    module: 'AUTH',
    severity: 'WARNING',
    httpStatus: 401,
    messageEn: 'Authentication token is missing',
    messageHi: 'प्रमाणीकरण टोकन गायब है',
    solutionEn: 'Include a valid Bearer token in the Authorization header.',
    solutionHi: 'Authorization हेडर में एक मान्य Bearer टोकन शामिल करें।',
  },
  {
    code: 'AUTH_TOKEN_EXPIRED',
    layer: 'BE',
    module: 'AUTH',
    severity: 'WARNING',
    httpStatus: 401,
    messageEn: 'Authentication token has expired',
    messageHi: 'प्रमाणीकरण टोकन समाप्त हो गया है',
    solutionEn: 'Obtain a new token via POST /auth/login.',
    solutionHi: 'POST /auth/login के माध्यम से एक नया टोकन प्राप्त करें।',
  },
  {
    code: 'AUTH_TOKEN_INVALID',
    layer: 'BE',
    module: 'AUTH',
    severity: 'ERROR',
    httpStatus: 401,
    messageEn: 'Authentication token is invalid or malformed',
    messageHi: 'प्रमाणीकरण टोकन अमान्य या विकृत है',
    solutionEn: 'Ensure the token is correctly formatted and not tampered with.',
    solutionHi: 'सुनिश्चित करें कि टोकन सही ढंग से स्वरूपित है और उसमें कोई छेड़छाड़ नहीं हुई है।',
  },
  {
    code: 'AUTH_INVALID_CREDENTIALS',
    layer: 'BE',
    module: 'AUTH',
    severity: 'WARNING',
    httpStatus: 401,
    messageEn: 'Invalid email or password',
    messageHi: 'अमान्य ईमेल या पासवर्ड',
    solutionEn: 'Check your email and password. Use POST /auth/forgot-password if needed.',
    solutionHi: 'अपना ईमेल और पासवर्ड जांचें। यदि आवश्यक हो तो पासवर्ड भूल गए का उपयोग करें।',
  },
  {
    code: 'AUTH_ACCOUNT_LOCKED',
    layer: 'BE',
    module: 'AUTH',
    severity: 'ERROR',
    httpStatus: 423,
    messageEn: 'Account is locked due to too many failed login attempts',
    messageHi: 'बहुत अधिक विफल लॉगिन प्रयासों के कारण खाता लॉक है',
    solutionEn: 'Wait 30 minutes or contact your admin to unlock.',
    solutionHi: '30 मिनट प्रतीक्षा करें या अनलॉक करने के लिए अपने व्यवस्थापक से संपर्क करें।',
  },
  {
    code: 'FORBIDDEN',
    layer: 'BE',
    module: 'AUTH',
    severity: 'WARNING',
    httpStatus: 403,
    messageEn: 'You do not have permission to perform this action',
    messageHi: 'आपको यह कार्य करने की अनुमति नहीं है',
    solutionEn: 'Contact your admin to get the required role/permission.',
    solutionHi: 'आवश्यक भूमिका/अनुमति प्राप्त करने के लिए अपने व्यवस्थापक से संपर्क करें।',
  },
  {
    code: 'PERMISSION_DENIED',
    layer: 'BE',
    module: 'AUTH',
    severity: 'WARNING',
    httpStatus: 403,
    messageEn: 'You lack the specific permission required for this action',
    messageHi: 'इस कार्य के लिए आवश्यक विशिष्ट अनुमति आपके पास नहीं है',
    solutionEn: 'Ask your admin to grant the required permission.',
    solutionHi: 'अपने व्यवस्थापक से आवश्यक अनुमति प्रदान करने के लिए कहें।',
  },

  // ═══════════════════════════════════════════════════
  // TENANT & SUBSCRIPTION (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'TENANT_NOT_FOUND',
    layer: 'BE',
    module: 'TENANT',
    severity: 'ERROR',
    httpStatus: 404,
    messageEn: 'Tenant does not exist',
    messageHi: 'टेनेंट मौजूद नहीं है',
    solutionEn: 'Verify the tenant slug or ID. Check if the account has been created.',
    solutionHi: 'टेनेंट स्लग या ID सत्यापित करें। जांचें कि खाता बनाया गया है या नहीं।',
  },
  {
    code: 'PLAN_LIMIT_REACHED',
    layer: 'BE',
    module: 'SUBSCRIPTION',
    severity: 'WARNING',
    httpStatus: 403,
    messageEn: 'You have reached the limit for your current plan',
    messageHi: 'आपने अपनी वर्तमान योजना की सीमा पूरी कर ली है',
    solutionEn: 'Upgrade your plan to increase limits.',
    solutionHi: 'सीमा बढ़ाने के लिए अपनी योजना अपग्रेड करें।',
  },
  {
    code: 'FEATURE_DISABLED',
    layer: 'BE',
    module: 'SUBSCRIPTION',
    severity: 'WARNING',
    httpStatus: 403,
    messageEn: 'This feature is not available on your current plan',
    messageHi: 'यह सुविधा आपकी वर्तमान योजना पर उपलब्ध नहीं है',
    solutionEn: 'Upgrade your plan to unlock this feature.',
    solutionHi: 'इस सुविधा को अनलॉक करने के लिए अपनी योजना अपग्रेड करें।',
  },
  {
    code: 'SUBSCRIPTION_EXPIRED',
    layer: 'BE',
    module: 'SUBSCRIPTION',
    severity: 'ERROR',
    httpStatus: 403,
    messageEn: 'Your subscription has expired',
    messageHi: 'आपकी सदस्यता समाप्त हो गई है',
    solutionEn: 'Renew your subscription to continue using the service.',
    solutionHi: 'सेवा का उपयोग जारी रखने के लिए अपनी सदस्यता नवीनीकृत करें।',
  },

  // ═══════════════════════════════════════════════════
  // DOMAIN ENTITIES (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'CONTACT_NOT_FOUND',
    layer: 'BE',
    module: 'CONTACTS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Contact does not exist',
    messageHi: 'संपर्क मौजूद नहीं है',
    solutionEn: 'Verify the contact ID. Use GET /contacts to list all contacts.',
    solutionHi: 'संपर्क ID सत्यापित करें। सभी संपर्कों की सूची के लिए GET /contacts का उपयोग करें।',
  },
  {
    code: 'CONTACT_DUPLICATE',
    layer: 'BE',
    module: 'CONTACTS',
    severity: 'WARNING',
    httpStatus: 409,
    messageEn: 'A contact with this email or phone already exists',
    messageHi: 'इस ईमेल या फ़ोन वाला संपर्क पहले से मौजूद है',
    solutionEn: 'Search for existing contacts before creating a new one.',
    solutionHi: 'नया बनाने से पहले मौजूदा संपर्कों की खोज करें।',
  },
  {
    code: 'LEAD_NOT_FOUND',
    layer: 'BE',
    module: 'LEADS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Lead does not exist',
    messageHi: 'लीड मौजूद नहीं है',
    solutionEn: 'Verify the lead ID. Use GET /leads to list all leads.',
    solutionHi: 'लीड ID सत्यापित करें। सभी लीड्स की सूची के लिए GET /leads का उपयोग करें।',
  },
  {
    code: 'LEAD_STAGE_INVALID',
    layer: 'BE',
    module: 'LEADS',
    severity: 'WARNING',
    httpStatus: 422,
    messageEn: 'Cannot move lead to this stage from the current stage',
    messageHi: 'वर्तमान चरण से लीड को इस चरण में नहीं ले जा सकते',
    solutionEn: 'Check valid stage transitions in the workflow configuration.',
    solutionHi: 'वर्कफ़्लो कॉन्फ़िगरेशन में मान्य चरण संक्रमण जांचें।',
  },
  {
    code: 'ORGANIZATION_NOT_FOUND',
    layer: 'BE',
    module: 'ORGANIZATIONS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Organization does not exist',
    messageHi: 'संगठन मौजूद नहीं है',
    solutionEn: 'Verify the organization ID.',
    solutionHi: 'संगठन ID सत्यापित करें।',
  },
  {
    code: 'QUOTATION_NOT_FOUND',
    layer: 'BE',
    module: 'QUOTATIONS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Quotation does not exist',
    messageHi: 'कोटेशन मौजूद नहीं है',
    solutionEn: 'Verify the quotation ID.',
    solutionHi: 'कोटेशन ID सत्यापित करें।',
  },
  {
    code: 'PRODUCT_NOT_FOUND',
    layer: 'BE',
    module: 'PRODUCTS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Product does not exist',
    messageHi: 'उत्पाद मौजूद नहीं है',
    solutionEn: 'Verify the product ID. Use GET /products to list all products.',
    solutionHi: 'उत्पाद ID सत्यापित करें। सभी उत्पादों की सूची के लिए GET /products का उपयोग करें।',
  },

  // ═══════════════════════════════════════════════════
  // DATABASE (DB)
  // ═══════════════════════════════════════════════════
  {
    code: 'DB_UNIQUE_CONSTRAINT',
    layer: 'DB',
    module: 'DATABASE',
    severity: 'WARNING',
    httpStatus: 409,
    messageEn: 'Unique constraint violation — duplicate value',
    messageHi: 'अद्वितीय बाधा उल्लंघन — डुप्लिकेट मान',
    solutionEn: 'Check for existing records with the same unique field value.',
    solutionHi: 'समान अद्वितीय फ़ील्ड मान वाले मौजूदा रिकॉर्ड की जांच करें।',
  },
  {
    code: 'DB_RECORD_NOT_FOUND',
    layer: 'DB',
    module: 'DATABASE',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Database record not found',
    messageHi: 'डेटाबेस रिकॉर्ड नहीं मिला',
    solutionEn: 'The referenced record may have been deleted. Verify the ID.',
    solutionHi: 'संदर्भित रिकॉर्ड हटा दिया गया हो सकता है। ID सत्यापित करें।',
  },
  {
    code: 'DB_FK_VIOLATION',
    layer: 'DB',
    module: 'DATABASE',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'Foreign key constraint violation — referenced record does not exist',
    messageHi: 'फॉरेन की बाधा उल्लंघन — संदर्भित रिकॉर्ड मौजूद नहीं है',
    solutionEn: 'Verify all referenced IDs (foreign keys) exist before creating/updating.',
    solutionHi: 'बनाने/अपडेट करने से पहले सत्यापित करें कि सभी संदर्भित ID (फॉरेन की) मौजूद हैं।',
  },
  {
    code: 'DB_CONNECTION_FAILED',
    layer: 'DB',
    module: 'DATABASE',
    severity: 'CRITICAL',
    httpStatus: 503,
    messageEn: 'Database connection failed',
    messageHi: 'डेटाबेस कनेक्शन विफल',
    solutionEn: 'Check database server status and connection string.',
    solutionHi: 'डेटाबेस सर्वर स्थिति और कनेक्शन स्ट्रिंग की जांच करें।',
  },

  // ═══════════════════════════════════════════════════
  // INTEGRATIONS (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'EMAIL_SEND_FAILED',
    layer: 'BE',
    module: 'EMAIL',
    severity: 'ERROR',
    httpStatus: 502,
    messageEn: 'Failed to send email',
    messageHi: 'ईमेल भेजने में विफल',
    solutionEn: 'Check email credentials and SMTP configuration.',
    solutionHi: 'ईमेल क्रेडेंशियल और SMTP कॉन्फ़िगरेशन जांचें।',
  },
  {
    code: 'EMAIL_TEMPLATE_NOT_FOUND',
    layer: 'BE',
    module: 'EMAIL',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Email template not found',
    messageHi: 'ईमेल टेम्प्लेट नहीं मिला',
    solutionEn: 'Verify the template ID or create a new template.',
    solutionHi: 'टेम्प्लेट ID सत्यापित करें या नया टेम्प्लेट बनाएं।',
  },
  {
    code: 'WHATSAPP_SEND_FAILED',
    layer: 'BE',
    module: 'WHATSAPP',
    severity: 'ERROR',
    httpStatus: 502,
    messageEn: 'Failed to send WhatsApp message',
    messageHi: 'WhatsApp संदेश भेजने में विफल',
    solutionEn: 'Check WhatsApp Business API credentials and connection status.',
    solutionHi: 'WhatsApp Business API क्रेडेंशियल और कनेक्शन स्थिति जांचें।',
  },
  {
    code: 'WHATSAPP_NOT_CONFIGURED',
    layer: 'BE',
    module: 'WHATSAPP',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'WhatsApp integration is not configured for this tenant',
    messageHi: 'इस टेनेंट के लिए WhatsApp एकीकरण कॉन्फ़िगर नहीं है',
    solutionEn: 'Configure WhatsApp credentials in Settings > Integrations.',
    solutionHi: 'सेटिंग्स > एकीकरण में WhatsApp क्रेडेंशियल कॉन्फ़िगर करें।',
  },

  // ═══════════════════════════════════════════════════
  // WORKFLOW (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'WORKFLOW_EXECUTION_FAILED',
    layer: 'BE',
    module: 'WORKFLOWS',
    severity: 'ERROR',
    httpStatus: 500,
    messageEn: 'Workflow execution failed',
    messageHi: 'वर्कफ़्लो निष्पादन विफल',
    solutionEn: 'Check the workflow configuration and retry.',
    solutionHi: 'वर्कफ़्लो कॉन्फ़िगरेशन जांचें और पुनः प्रयास करें।',
  },
  {
    code: 'WORKFLOW_NOT_FOUND',
    layer: 'BE',
    module: 'WORKFLOWS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Workflow does not exist',
    messageHi: 'वर्कफ़्लो मौजूद नहीं है',
    solutionEn: 'Verify the workflow ID.',
    solutionHi: 'वर्कफ़्लो ID सत्यापित करें।',
  },

  // ═══════════════════════════════════════════════════
  // IMPORT / EXPORT (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'IMPORT_FILE_INVALID',
    layer: 'BE',
    module: 'IMPORT',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'Import file is invalid or corrupted',
    messageHi: 'आयात फ़ाइल अमान्य या दूषित है',
    solutionEn: 'Ensure the file is a valid CSV/XLSX and follows the required template.',
    solutionHi: 'सुनिश्चित करें कि फ़ाइल एक मान्य CSV/XLSX है और आवश्यक टेम्प्लेट का अनुसरण करती है।',
  },
  {
    code: 'EXPORT_FAILED',
    layer: 'BE',
    module: 'EXPORT',
    severity: 'ERROR',
    httpStatus: 500,
    messageEn: 'Data export failed',
    messageHi: 'डेटा निर्यात विफल',
    solutionEn: 'Retry the export. If persists, try reducing the data range.',
    solutionHi: 'निर्यात पुनः प्रयास करें। यदि बनी रहे, तो डेटा रेंज कम करने का प्रयास करें।',
  },

  // ═══════════════════════════════════════════════════
  // CREDENTIALS & ENCRYPTION (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'ENCRYPTION_FAILED',
    layer: 'BE',
    module: 'SECURITY',
    severity: 'CRITICAL',
    httpStatus: 500,
    messageEn: 'Encryption operation failed',
    messageHi: 'एन्क्रिप्शन ऑपरेशन विफल',
    solutionEn: 'Check encryption key configuration. Contact system administrator.',
    solutionHi: 'एन्क्रिप्शन कुंजी कॉन्फ़िगरेशन जांचें। सिस्टम व्यवस्थापक से संपर्क करें।',
  },
  {
    code: 'CREDENTIAL_VERIFICATION_FAILED',
    layer: 'BE',
    module: 'SECURITY',
    severity: 'ERROR',
    httpStatus: 400,
    messageEn: 'Credential verification failed',
    messageHi: 'क्रेडेंशियल सत्यापन विफल',
    solutionEn: 'Re-enter valid credentials. Ensure API keys are active.',
    solutionHi: 'मान्य क्रेडेंशियल पुनः दर्ज करें। सुनिश्चित करें कि API कुंजियां सक्रिय हैं।',
  },

  // ═══════════════════════════════════════════════════
  // FRONTEND (FE)
  // ═══════════════════════════════════════════════════
  {
    code: 'FE_NETWORK_ERROR',
    layer: 'FE',
    module: 'FRONTEND',
    severity: 'ERROR',
    httpStatus: 0,
    messageEn: 'Network request failed — server unreachable',
    messageHi: 'नेटवर्क अनुरोध विफल — सर्वर अनुपलब्ध',
    solutionEn: 'Check your internet connection and try again.',
    solutionHi: 'अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।',
  },
  {
    code: 'FE_RENDER_ERROR',
    layer: 'FE',
    module: 'FRONTEND',
    severity: 'ERROR',
    httpStatus: 0,
    messageEn: 'UI component failed to render',
    messageHi: 'UI कंपोनेंट रेंडर करने में विफल',
    solutionEn: 'Refresh the page. If the issue persists, clear browser cache.',
    solutionHi: 'पेज रिफ्रेश करें। यदि समस्या बनी रहे, तो ब्राउज़र कैश साफ़ करें।',
  },
  {
    code: 'FE_SESSION_EXPIRED',
    layer: 'FE',
    module: 'FRONTEND',
    severity: 'WARNING',
    httpStatus: 401,
    messageEn: 'Your session has expired. Please log in again.',
    messageHi: 'आपका सत्र समाप्त हो गया है। कृपया पुनः लॉगिन करें।',
    solutionEn: 'Log in again to continue.',
    solutionHi: 'जारी रखने के लिए पुनः लॉगिन करें।',
  },
  {
    code: 'FE_FORM_VALIDATION',
    layer: 'FE',
    module: 'FRONTEND',
    severity: 'INFO',
    httpStatus: 0,
    messageEn: 'Form validation failed — please fix highlighted fields',
    messageHi: 'फॉर्म सत्यापन विफल — कृपया हाइलाइट किए गए फ़ील्ड ठीक करें',
    solutionEn: 'Fill in all required fields correctly before submitting.',
    solutionHi: 'सबमिट करने से पहले सभी आवश्यक फ़ील्ड सही ढंग से भरें।',
  },

  // ═══════════════════════════════════════════════════
  // MOBILE (MOB)
  // ═══════════════════════════════════════════════════
  {
    code: 'MOB_SYNC_FAILED',
    layer: 'MOB',
    module: 'MOBILE',
    severity: 'ERROR',
    httpStatus: 0,
    messageEn: 'Offline data sync failed',
    messageHi: 'ऑफ़लाइन डेटा सिंक विफल',
    solutionEn: 'Check your internet connection and try syncing again.',
    solutionHi: 'अपना इंटरनेट कनेक्शन जांचें और पुनः सिंक करने का प्रयास करें।',
  },
  {
    code: 'MOB_GPS_UNAVAILABLE',
    layer: 'MOB',
    module: 'MOBILE',
    severity: 'WARNING',
    httpStatus: 0,
    messageEn: 'GPS location is unavailable',
    messageHi: 'GPS स्थान अनुपलब्ध है',
    solutionEn: 'Enable location services and grant GPS permission to the app.',
    solutionHi: 'लोकेशन सेवाएं सक्षम करें और ऐप को GPS अनुमति दें।',
  },

  // ═══════════════════════════════════════════════════
  // DOCUMENT & STORAGE (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'DOCUMENT_UPLOAD_FAILED',
    layer: 'BE',
    module: 'DOCUMENTS',
    severity: 'ERROR',
    httpStatus: 500,
    messageEn: 'File upload failed',
    messageHi: 'फ़ाइल अपलोड विफल',
    solutionEn: 'Check file size limits and storage configuration.',
    solutionHi: 'फ़ाइल आकार सीमा और स्टोरेज कॉन्फ़िगरेशन जांचें।',
  },
  {
    code: 'DOCUMENT_NOT_FOUND',
    layer: 'BE',
    module: 'DOCUMENTS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Document does not exist',
    messageHi: 'दस्तावेज़ मौजूद नहीं है',
    solutionEn: 'Verify the document ID.',
    solutionHi: 'दस्तावेज़ ID सत्यापित करें।',
  },

  // ═══════════════════════════════════════════════════
  // VERIFICATION (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'VERIFICATION_REQUIRED',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'WARNING',
    httpStatus: 403,
    messageEn: 'Please verify your email and mobile to continue',
    messageHi: 'जारी रखने के लिए कृपया अपना ईमेल और मोबाइल सत्यापित करें',
    solutionEn: 'Go to Settings → Verification to verify your account.',
    solutionHi: 'अपना खाता सत्यापित करने के लिए सेटिंग्स → सत्यापन पर जाएं।',
  },
  {
    code: 'OTP_EXPIRED',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'OTP has expired. Please request a new one.',
    messageHi: 'OTP समाप्त हो गया है। कृपया एक नया अनुरोध करें।',
    solutionEn: 'Click "Resend OTP" to get a new code.',
    solutionHi: 'नया कोड प्राप्त करने के लिए "OTP पुनः भेजें" पर क्लिक करें।',
    isRetryable: true,
  },
  {
    code: 'OTP_INVALID',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'Invalid OTP. Please check and try again.',
    messageHi: 'अमान्य OTP। कृपया जांचें और पुनः प्रयास करें।',
    solutionEn: 'Enter the 6-digit code sent to your email/phone.',
    solutionHi: 'अपने ईमेल/फोन पर भेजा गया 6 अंकों का कोड दर्ज करें।',
    isRetryable: true,
  },
  {
    code: 'OTP_MAX_ATTEMPTS',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'ERROR',
    httpStatus: 429,
    messageEn: 'Too many OTP attempts. Please request a new OTP.',
    messageHi: 'बहुत अधिक OTP प्रयास। कृपया एक नया OTP अनुरोध करें।',
    solutionEn: 'Wait 60 seconds then request a new OTP.',
    solutionHi: '60 सेकंड प्रतीक्षा करें फिर नया OTP अनुरोध करें।',
    isRetryable: true,
    retryAfterMs: 60000,
  },
  {
    code: 'GST_INVALID_FORMAT',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'ERROR',
    httpStatus: 400,
    messageEn: 'Invalid GST number format',
    messageHi: 'अमान्य GST नंबर प्रारूप',
    solutionEn: 'GST number should be 15 characters (e.g., 27AABCU9603R1ZM).',
    solutionHi: 'GST नंबर 15 अक्षरों का होना चाहिए (जैसे, 27AABCU9603R1ZM)।',
    helpUrl: '/help/verification/gst',
    isRetryable: true,
  },
  {
    code: 'GST_ALREADY_REGISTERED',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'WARNING',
    httpStatus: 409,
    messageEn: 'This GST number is already registered with another account',
    messageHi: 'यह GST नंबर पहले से किसी अन्य खाते से पंजीकृत है',
    solutionEn: 'Contact support if you believe this is an error.',
    solutionHi: 'यदि आपको लगता है कि यह त्रुटि है तो सहायता से संपर्क करें।',
  },
  {
    code: 'EMAIL_ALREADY_VERIFIED',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'INFO',
    httpStatus: 400,
    messageEn: 'Email is already verified',
    messageHi: 'ईमेल पहले से सत्यापित है',
    solutionEn: 'No action needed — your email is already verified.',
    solutionHi: 'कोई कार्रवाई आवश्यक नहीं — आपका ईमेल पहले से सत्यापित है।',
  },
  {
    code: 'MOBILE_ALREADY_VERIFIED',
    layer: 'BE',
    module: 'VERIFICATION',
    severity: 'INFO',
    httpStatus: 400,
    messageEn: 'Mobile is already verified',
    messageHi: 'मोबाइल पहले से सत्यापित है',
    solutionEn: 'No action needed — your mobile is already verified.',
    solutionHi: 'कोई कार्रवाई आवश्यक नहीं — आपका मोबाइल पहले से सत्यापित है।',
  },

  // ═══════════════════════════════════════════════════
  // MARKETPLACE (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'LISTING_NOT_FOUND',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Listing not found',
    messageHi: 'लिस्टिंग नहीं मिली',
    solutionEn: 'The listing may have been removed or expired.',
    solutionHi: 'लिस्टिंग हटाई गई या समाप्त हो सकती है।',
  },
  {
    code: 'LISTING_EXPIRED',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 410,
    messageEn: 'This listing has expired',
    messageHi: 'यह लिस्टिंग समाप्त हो गई है',
    solutionEn: 'Contact the vendor for availability.',
    solutionHi: 'उपलब्धता के लिए विक्रेता से संपर्क करें।',
  },
  {
    code: 'LISTING_INACTIVE',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'This listing is not currently active',
    messageHi: 'यह लिस्टिंग वर्तमान में सक्रिय नहीं है',
    solutionEn: 'The vendor may have paused this listing.',
    solutionHi: 'विक्रेता ने इस लिस्टिंग को रोक दिया हो सकता है।',
  },
  {
    code: 'B2B_VERIFICATION_REQUIRED',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 403,
    messageEn: 'B2B pricing requires GST verification',
    messageHi: 'B2B मूल्य निर्धारण के लिए GST सत्यापन आवश्यक है',
    solutionEn: 'Verify your GST number to access wholesale pricing.',
    solutionHi: 'थोक मूल्य निर्धारण तक पहुंचने के लिए अपना GST नंबर सत्यापित करें।',
    helpUrl: '/help/marketplace/b2b-pricing',
  },
  {
    code: 'ENQUIRY_NOT_FOUND',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Enquiry not found',
    messageHi: 'पूछताछ नहीं मिली',
    solutionEn: 'Verify the enquiry ID.',
    solutionHi: 'पूछताछ ID सत्यापित करें।',
  },
  {
    code: 'ORDER_NOT_FOUND',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Order not found',
    messageHi: 'ऑर्डर नहीं मिला',
    solutionEn: 'Verify the order ID or order number.',
    solutionHi: 'ऑर्डर ID या ऑर्डर नंबर सत्यापित करें।',
  },
  {
    code: 'ORDER_EMPTY_ITEMS',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'Order must contain at least one item',
    messageHi: 'ऑर्डर में कम से कम एक आइटम होना चाहिए',
    solutionEn: 'Add items to your order before submitting.',
    solutionHi: 'सबमिट करने से पहले अपने ऑर्डर में आइटम जोड़ें।',
  },
  {
    code: 'POST_NOT_FOUND',
    layer: 'BE',
    module: 'MARKETPLACE',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Post not found',
    messageHi: 'पोस्ट नहीं मिली',
    solutionEn: 'The post may have been deleted.',
    solutionHi: 'पोस्ट हटाई जा चुकी हो सकती है।',
  },

  // ═══════════════════════════════════════════════════
  // PLUGIN (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'PLUGIN_NOT_CONFIGURED',
    layer: 'BE',
    module: 'PLUGINS',
    severity: 'ERROR',
    httpStatus: 400,
    messageEn: 'Plugin is not configured',
    messageHi: 'प्लगइन कॉन्फ़िगर नहीं है',
    solutionEn: 'Go to Settings → Integrations to configure the plugin.',
    solutionHi: 'प्लगइन कॉन्फ़िगर करने के लिए सेटिंग्स → इंटीग्रेशन पर जाएं।',
  },
  {
    code: 'PLUGIN_CREDENTIALS_INVALID',
    layer: 'BE',
    module: 'PLUGINS',
    severity: 'ERROR',
    httpStatus: 401,
    messageEn: 'Plugin credentials are invalid',
    messageHi: 'प्लगइन क्रेडेंशियल अमान्य हैं',
    solutionEn: 'Update the API credentials in Settings → Integrations.',
    solutionHi: 'सेटिंग्स → इंटीग्रेशन में API क्रेडेंशियल अपडेट करें।',
    isRetryable: true,
  },
  {
    code: 'PLUGIN_API_FAILED',
    layer: 'BE',
    module: 'PLUGINS',
    severity: 'ERROR',
    httpStatus: 502,
    messageEn: 'External plugin API request failed',
    messageHi: 'बाहरी प्लगइन API अनुरोध विफल',
    solutionEn: 'Try again. If the issue persists, check the plugin status.',
    solutionHi: 'पुनः प्रयास करें। यदि समस्या बनी रहे, तो प्लगइन स्थिति जांचें।',
    isRetryable: true,
    retryAfterMs: 5000,
  },

  // ═══════════════════════════════════════════════════
  // INVOICE & PAYMENT (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'INVOICE_NOT_FOUND',
    layer: 'BE',
    module: 'FINANCE',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Invoice does not exist',
    messageHi: 'इनवॉइस मौजूद नहीं है',
    solutionEn: 'Verify the invoice ID or invoice number.',
    solutionHi: 'इनवॉइस ID या इनवॉइस नंबर सत्यापित करें।',
  },
  {
    code: 'INVOICE_ALREADY_PAID',
    layer: 'BE',
    module: 'FINANCE',
    severity: 'INFO',
    httpStatus: 400,
    messageEn: 'This invoice has already been paid',
    messageHi: 'इस इनवॉइस का भुगतान पहले ही हो चुका है',
    solutionEn: 'Check payment history for this invoice.',
    solutionHi: 'इस इनवॉइस के लिए भुगतान इतिहास जांचें।',
  },
  {
    code: 'PAYMENT_FAILED',
    layer: 'BE',
    module: 'FINANCE',
    severity: 'ERROR',
    httpStatus: 402,
    messageEn: 'Payment processing failed',
    messageHi: 'भुगतान प्रसंस्करण विफल',
    solutionEn: 'Check payment details and try again. Contact your bank if the issue persists.',
    solutionHi: 'भुगतान विवरण जांचें और पुनः प्रयास करें। यदि समस्या बनी रहे तो अपने बैंक से संपर्क करें।',
    isRetryable: true,
  },
  {
    code: 'PAYMENT_NOT_FOUND',
    layer: 'BE',
    module: 'FINANCE',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Payment record not found',
    messageHi: 'भुगतान रिकॉर्ड नहीं मिला',
    solutionEn: 'Verify the payment ID.',
    solutionHi: 'भुगतान ID सत्यापित करें।',
  },

  // ═══════════════════════════════════════════════════
  // ACTIVITY & TOUR PLAN (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'ACTIVITY_NOT_FOUND',
    layer: 'BE',
    module: 'ACTIVITIES',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Activity does not exist',
    messageHi: 'गतिविधि मौजूद नहीं है',
    solutionEn: 'Verify the activity ID.',
    solutionHi: 'गतिविधि ID सत्यापित करें।',
  },
  {
    code: 'TOUR_PLAN_CONFLICT',
    layer: 'BE',
    module: 'ACTIVITIES',
    severity: 'WARNING',
    httpStatus: 409,
    messageEn: 'A tour plan already exists for this date',
    messageHi: 'इस तारीख के लिए पहले से एक टूर प्लान मौजूद है',
    solutionEn: 'Edit the existing tour plan or choose a different date.',
    solutionHi: 'मौजूदा टूर प्लान संपादित करें या कोई अलग तारीख चुनें।',
  },

  // ═══════════════════════════════════════════════════
  // TICKET & POST-SALES (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'TICKET_NOT_FOUND',
    layer: 'BE',
    module: 'TICKETS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Support ticket does not exist',
    messageHi: 'सपोर्ट टिकट मौजूद नहीं है',
    solutionEn: 'Verify the ticket ID or ticket number.',
    solutionHi: 'टिकट ID या टिकट नंबर सत्यापित करें।',
  },
  {
    code: 'TICKET_CLOSED',
    layer: 'BE',
    module: 'TICKETS',
    severity: 'INFO',
    httpStatus: 400,
    messageEn: 'This ticket has been closed',
    messageHi: 'यह टिकट बंद हो गया है',
    solutionEn: 'Reopen the ticket or create a new one.',
    solutionHi: 'टिकट फिर से खोलें या नया बनाएं।',
  },

  // ═══════════════════════════════════════════════════
  // SETTINGS & CONFIGURATION (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'ROLE_IN_USE',
    layer: 'BE',
    module: 'SETTINGS',
    severity: 'WARNING',
    httpStatus: 409,
    messageEn: 'This role is assigned to users and cannot be deleted',
    messageHi: 'यह भूमिका उपयोगकर्ताओं को सौंपी गई है और इसे हटाया नहीं जा सकता',
    solutionEn: 'Reassign users to a different role before deleting.',
    solutionHi: 'हटाने से पहले उपयोगकर्ताओं को एक अलग भूमिका सौंपें।',
  },
  {
    code: 'LOOKUP_NOT_FOUND',
    layer: 'BE',
    module: 'SETTINGS',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Lookup value does not exist',
    messageHi: 'लुकअप मान मौजूद नहीं है',
    solutionEn: 'Check available lookup values in Settings → Lookups.',
    solutionHi: 'सेटिंग्स → लुकअप में उपलब्ध लुकअप मान जांचें।',
  },

  // ═══════════════════════════════════════════════════
  // PROCUREMENT (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'PURCHASE_ORDER_SALE_ORDER_NOT_FOUND',
    layer: 'BE',
    module: 'PROCUREMENT',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Sale Order not found',
    messageHi: 'सेल ऑर्डर नहीं मिला',
    solutionEn: 'Check the Sale Order ID and verify it belongs to your account.',
    solutionHi: 'सेल ऑर्डर ID जांचें और सत्यापित करें कि यह आपके खाते से संबंधित है।',
  },

  // ═══════════════════════════════════════════════════
  // CUSTOMER PORTAL (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'PORTAL_INVITE_REQUIRES_VERIFICATION',
    layer: 'BE',
    module: 'CUSTOMER_PORTAL',
    severity: 'ERROR',
    httpStatus: 400,
    messageEn: 'Contact or organization must be verified before portal invite',
    messageHi: 'पोर्टल निमंत्रण से पहले संपर्क या संगठन सत्यापित होना चाहिए',
    solutionEn: 'Complete entity verification first (email/GST/document).',
    solutionHi: 'पहले एंटिटी सत्यापन पूरा करें (ईमेल/GST/दस्तावेज़)।',
  },
  {
    code: 'PORTAL_INVITE_NO_EMAIL',
    layer: 'BE',
    module: 'CUSTOMER_PORTAL',
    severity: 'ERROR',
    httpStatus: 400,
    messageEn: 'Recipient has no email address on record',
    messageHi: 'प्राप्तकर्ता के पास कोई ईमेल नहीं है',
    solutionEn: 'Add email to the contact or organization first.',
    solutionHi: 'पहले संपर्क या संगठन में ईमेल जोड़ें।',
  },
  {
    code: 'PORTAL_INVITE_DELIVERY_PARTIAL',
    layer: 'BE',
    module: 'CUSTOMER_PORTAL',
    severity: 'WARNING',
    httpStatus: 200,
    messageEn: 'Portal activated but some delivery channels skipped or failed',
    messageHi: 'पोर्टल सक्रिय हुआ लेकिन कुछ चैनल छूट गए या विफल रहे',
    solutionEn: 'Review the communication log and share credentials manually if needed.',
    solutionHi: 'संचार लॉग देखें और आवश्यकतानुसार क्रेडेंशियल्स मैन्युअल भेजें।',
  },
  {
    code: 'PORTAL_INVITE_PLUGIN_STUB',
    layer: 'BE',
    module: 'CUSTOMER_PORTAL',
    severity: 'INFO',
    httpStatus: 200,
    messageEn: 'Credentials queued — plugin delivery pending implementation',
    messageHi: 'क्रेडेंशियल्स क्यू में — प्लगइन डिलीवरी लंबित है',
    solutionEn: 'Use the temporary password in the admin response to onboard the customer manually.',
    solutionHi: 'ग्राहक को मैन्युअल रूप से ऑनबोर्ड करने के लिए एडमिन प्रतिक्रिया में दिखाया गया अस्थायी पासवर्ड उपयोग करें।',
  },

  // ═══════════════════════════════════════════════════
  // COMMUNICATION LOG (BE)
  // ═══════════════════════════════════════════════════
  {
    code: 'COMMUNICATION_LOG_NOT_FOUND',
    layer: 'BE',
    module: 'CUSTOMER_PORTAL',
    severity: 'WARNING',
    httpStatus: 404,
    messageEn: 'Communication log entry not found',
    messageHi: 'संचार लॉग प्रविष्टि नहीं मिली',
    solutionEn: 'Refresh the list and retry with a current entry ID.',
    solutionHi: 'सूची को रिफ़्रेश करें और मौजूदा प्रविष्टि ID से पुनः प्रयास करें।',
  },
  {
    code: 'COMMUNICATION_LOG_CANNOT_RETRY_SENT',
    layer: 'BE',
    module: 'CUSTOMER_PORTAL',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'This communication was already delivered and cannot be retried',
    messageHi: 'यह संचार पहले ही डिलीवर हो चुका है, पुनः प्रयास नहीं किया जा सकता',
    solutionEn: 'Only FAILED or SKIPPED entries can be retried.',
    solutionHi: 'केवल FAILED या SKIPPED प्रविष्टियाँ पुनः भेजी जा सकती हैं।',
  },
  {
    code: 'COMMUNICATION_LOG_CHANNEL_NOT_SUPPORTED',
    layer: 'BE',
    module: 'CUSTOMER_PORTAL',
    severity: 'WARNING',
    httpStatus: 400,
    messageEn: 'Retry is not supported for this channel',
    messageHi: 'इस चैनल के लिए पुनः प्रयास समर्थित नहीं है',
    solutionEn: 'Retry is currently supported for EMAIL and WHATSAPP channels only.',
    solutionHi: 'पुनः प्रयास वर्तमान में केवल EMAIL और WHATSAPP चैनलों के लिए समर्थित है।',
  },
];

export async function seedErrorCatalog(prisma: PrismaClient): Promise<number> {
  let count = 0;
  for (const entry of ERROR_CATALOG_SEED) {
    await prisma.errorCatalog.upsert({
      where: { code: entry.code },
      update: {
        layer: entry.layer,
        module: entry.module,
        severity: entry.severity,
        httpStatus: entry.httpStatus,
        messageEn: entry.messageEn,
        messageHi: entry.messageHi,
        solutionEn: entry.solutionEn,
        solutionHi: entry.solutionHi,
        helpUrl: entry.helpUrl || null,
        isRetryable: entry.isRetryable || false,
        retryAfterMs: entry.retryAfterMs || null,
      },
      create: {
        code: entry.code,
        layer: entry.layer,
        module: entry.module,
        severity: entry.severity,
        httpStatus: entry.httpStatus,
        messageEn: entry.messageEn,
        messageHi: entry.messageHi,
        solutionEn: entry.solutionEn,
        solutionHi: entry.solutionHi,
        helpUrl: entry.helpUrl || null,
        isRetryable: entry.isRetryable || false,
        retryAfterMs: entry.retryAfterMs || null,
      },
    });
    count++;
  }
  return count;
}
