import { PrismaClient } from '@prisma/client';

export async function seedModulesAndPackages(prisma: PrismaClient) {
  console.log('--- Seeding Modules & Packages ---');

  // ── 1. Module Definitions ──────────────────────────────────────────

  const moduleDefs = [
    {
      code: 'contacts',
      name: 'Contact Management',
      description: 'Manage contacts, import/export, and contact dashboards',
      category: 'CORE' as const,
      isCore: true,
      sortOrder: 1,
      iconName: 'contact',
      dependsOn: [],
      features: [
        { code: 'contact_list', name: 'Contact List', type: 'PAGE', menuKey: 'crm.contacts', isDefault: true },
        { code: 'contact_create', name: 'Create Contact', type: 'PAGE', menuKey: 'crm.contacts.create', isDefault: true },
        { code: 'contact_edit', name: 'Edit Contact', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'contact_detail', name: 'Contact Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'contact_import', name: 'Bulk Import Contacts', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'contact_export', name: 'Export Contacts', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'contact_dashboard', name: 'Contact Dashboard', type: 'WIDGET', menuKey: 'crm.contacts.dashboard', isDefault: false },
        { code: 'contact_report', name: 'Contact Report', type: 'REPORT', menuKey: 'reports.contacts', isDefault: true },
      ],
      menuKeys: ['crm.contacts', 'crm.contacts.create', 'crm.contacts.dashboard', 'reports.contacts'],
      defaultPricingType: 'FREE' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'leads',
      name: 'Lead Management',
      description: 'Track leads through pipeline stages with scoring and kanban views',
      category: 'CRM' as const,
      isCore: false,
      sortOrder: 2,
      iconName: 'target',
      dependsOn: ['contacts'],
      features: [
        { code: 'lead_list', name: 'Lead List', type: 'PAGE', menuKey: 'crm.leads', isDefault: true },
        { code: 'lead_create', name: 'Create Lead', type: 'PAGE', menuKey: 'crm.leads.create', isDefault: true },
        { code: 'lead_edit', name: 'Edit Lead', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'lead_detail', name: 'Lead Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'lead_pipeline', name: 'Lead Pipeline', type: 'PAGE', menuKey: 'crm.leads.pipeline', isDefault: true },
        { code: 'lead_kanban', name: 'Lead Kanban', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'lead_scoring', name: 'Lead Scoring', type: 'ACTION', menuKey: null, isDefault: false },
        { code: 'lead_import', name: 'Bulk Import Leads', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'lead_report', name: 'Lead Report', type: 'REPORT', menuKey: 'reports.leads', isDefault: true },
      ],
      menuKeys: ['crm.leads', 'crm.leads.create', 'crm.leads.pipeline', 'reports.leads'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'products',
      name: 'Product Catalog',
      description: 'Manage products, categories, brands, and pricing',
      category: 'CORE' as const,
      isCore: true,
      sortOrder: 3,
      iconName: 'package',
      dependsOn: [],
      features: [
        { code: 'product_list', name: 'Product List', type: 'PAGE', menuKey: 'crm.products', isDefault: true },
        { code: 'product_create', name: 'Create Product', type: 'PAGE', menuKey: 'crm.products.create', isDefault: true },
        { code: 'product_edit', name: 'Edit Product', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'product_detail', name: 'Product Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'product_categories', name: 'Product Categories', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'product_brands', name: 'Product Brands', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'product_pricing', name: 'Product Pricing', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'product_import', name: 'Bulk Import Products', type: 'ACTION', menuKey: null, isDefault: true },
      ],
      menuKeys: ['crm.products', 'crm.products.create'],
      defaultPricingType: 'FREE' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'quotations',
      name: 'Quotation Management',
      description: 'Create and manage quotations with revision tracking and approvals',
      category: 'SALES' as const,
      isCore: false,
      sortOrder: 4,
      iconName: 'file-text',
      dependsOn: ['contacts', 'products'],
      features: [
        { code: 'quotation_list', name: 'Quotation List', type: 'PAGE', menuKey: 'crm.quotations', isDefault: true },
        { code: 'quotation_create', name: 'Create Quotation', type: 'PAGE', menuKey: 'crm.quotations.create', isDefault: true },
        { code: 'quotation_edit', name: 'Edit Quotation', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'quotation_detail', name: 'Quotation Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'quotation_revise', name: 'Revise Quotation', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'quotation_approve', name: 'Approve Quotation', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'quotation_pdf', name: 'Quotation PDF', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'quotation_report', name: 'Quotation Report', type: 'REPORT', menuKey: 'reports.quotations', isDefault: true },
      ],
      menuKeys: ['crm.quotations', 'crm.quotations.create', 'reports.quotations'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'invoices',
      name: 'Invoice Management',
      description: 'Generate invoices with GST calculations and payment links',
      category: 'FINANCE' as const,
      isCore: false,
      sortOrder: 5,
      iconName: 'receipt',
      dependsOn: ['quotations'],
      features: [
        { code: 'invoice_list', name: 'Invoice List', type: 'PAGE', menuKey: 'finance.invoices', isDefault: true },
        { code: 'invoice_create', name: 'Create Invoice', type: 'PAGE', menuKey: 'finance.invoices.create', isDefault: true },
        { code: 'invoice_edit', name: 'Edit Invoice', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'invoice_detail', name: 'Invoice Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'invoice_gst_calc', name: 'GST Calculator', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'invoice_pdf', name: 'Invoice PDF', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'invoice_payment_link', name: 'Payment Link', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'invoice_report', name: 'Invoice Report', type: 'REPORT', menuKey: 'reports.invoices', isDefault: true },
      ],
      menuKeys: ['finance.invoices', 'finance.invoices.create', 'reports.invoices'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'payments',
      name: 'Payment Collection',
      description: 'Record payments, integrate Razorpay, and generate receipts',
      category: 'FINANCE' as const,
      isCore: false,
      sortOrder: 6,
      iconName: 'credit-card',
      dependsOn: ['invoices'],
      features: [
        { code: 'payment_list', name: 'Payment List', type: 'PAGE', menuKey: 'finance.payments', isDefault: true },
        { code: 'payment_record', name: 'Record Payment', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'payment_razorpay', name: 'Razorpay Integration', type: 'INTEGRATION', menuKey: null, isDefault: true },
        { code: 'payment_receipt', name: 'Receipt Generation', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'payment_report', name: 'Payment Report', type: 'REPORT', menuKey: 'reports.payments', isDefault: true },
      ],
      menuKeys: ['finance.payments', 'reports.payments'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'whatsapp',
      name: 'WhatsApp Integration',
      description: 'Send messages, manage templates, chatbot, and broadcast',
      category: 'COMMUNICATION' as const,
      isCore: false,
      sortOrder: 7,
      iconName: 'message-circle',
      dependsOn: [],
      features: [
        { code: 'whatsapp_templates', name: 'WhatsApp Templates', type: 'PAGE', menuKey: 'communication.whatsapp', isDefault: true },
        { code: 'whatsapp_send', name: 'Send Message', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'whatsapp_chatbot', name: 'Chatbot', type: 'ACTION', menuKey: null, isDefault: false },
        { code: 'whatsapp_broadcast', name: 'Broadcast', type: 'ACTION', menuKey: null, isDefault: false },
        { code: 'whatsapp_report', name: 'WhatsApp Report', type: 'REPORT', menuKey: null, isDefault: true },
      ],
      menuKeys: ['communication.whatsapp'],
      defaultPricingType: 'ADDON' as const,
      basePrice: 499,
      priceMonthly: 499,
      priceYearly: 4990,
      trialDays: 14,
      requiresCredentials: true,
    },
    {
      code: 'tasks',
      name: 'Task Management',
      description: 'Create and track tasks with calendar and reminder support',
      category: 'OPERATIONS' as const,
      isCore: false,
      sortOrder: 8,
      iconName: 'check-square',
      dependsOn: [],
      features: [
        { code: 'task_list', name: 'Task List', type: 'PAGE', menuKey: 'operations.tasks', isDefault: true },
        { code: 'task_create', name: 'Create Task', type: 'PAGE', menuKey: 'operations.tasks.create', isDefault: true },
        { code: 'task_edit', name: 'Edit Task', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'task_calendar', name: 'Task Calendar', type: 'PAGE', menuKey: 'operations.calendar', isDefault: true },
        { code: 'task_reminders', name: 'Task Reminders', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'task_report', name: 'Task Report', type: 'REPORT', menuKey: null, isDefault: true },
      ],
      menuKeys: ['operations.tasks', 'operations.tasks.create', 'operations.calendar'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'reports',
      name: 'Advanced Reports',
      description: 'Build custom reports, schedule exports, and view dashboards',
      category: 'ANALYTICS' as const,
      isCore: false,
      sortOrder: 9,
      iconName: 'bar-chart-2',
      dependsOn: [],
      features: [
        { code: 'report_builder', name: 'Report Builder', type: 'PAGE', menuKey: 'reports.builder', isDefault: true },
        { code: 'report_scheduled', name: 'Scheduled Reports', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'report_export', name: 'Report Export', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'report_dashboard', name: 'Report Dashboard', type: 'PAGE', menuKey: 'reports.dashboard', isDefault: true },
        { code: 'report_custom', name: 'Custom Reports', type: 'REPORT', menuKey: null, isDefault: false },
      ],
      menuKeys: ['reports.builder', 'reports.dashboard'],
      defaultPricingType: 'ADDON' as const,
      basePrice: 299,
      priceMonthly: 299,
      priceYearly: 2990,
      trialDays: 7,
    },
    {
      code: 'inventory',
      name: 'Inventory Management',
      description: 'Serial tracking, stock in/out, locations, adjustments, and reports',
      category: 'OPERATIONS' as const,
      isCore: false,
      sortOrder: 11,
      iconName: 'warehouse',
      dependsOn: ['products'],
      features: [
        { code: 'inventory_dashboard', name: 'Inventory Dashboard', type: 'PAGE', menuKey: 'inventory.dashboard', isDefault: true },
        { code: 'serial_list', name: 'Serial / Key List', type: 'PAGE', menuKey: 'inventory.serials', isDefault: true },
        { code: 'serial_create', name: 'Add Serial / Key', type: 'PAGE', menuKey: 'inventory.serials.new', isDefault: true },
        { code: 'serial_bulk_import', name: 'Bulk Import Serials', type: 'ACTION', menuKey: 'inventory.serials.bulk-import', isDefault: true },
        { code: 'stock_transactions', name: 'Stock Transactions', type: 'PAGE', menuKey: 'inventory.transactions', isDefault: true },
        { code: 'stock_locations', name: 'Stock Locations', type: 'PAGE', menuKey: 'inventory.locations', isDefault: true },
        { code: 'stock_adjustments', name: 'Stock Adjustments', type: 'PAGE', menuKey: 'inventory.adjustments', isDefault: true },
        { code: 'inventory_reports', name: 'Inventory Reports', type: 'REPORT', menuKey: 'inventory.reports', isDefault: true },
        { code: 'stock_ledger', name: 'Stock Ledger', type: 'REPORT', menuKey: 'inventory.reports.ledger', isDefault: true },
        { code: 'expiry_report', name: 'Expiry Report', type: 'REPORT', menuKey: 'inventory.reports.expiry', isDefault: true },
        { code: 'valuation_report', name: 'Stock Valuation', type: 'REPORT', menuKey: 'inventory.reports.valuation', isDefault: true },
        { code: 'serial_tracking', name: 'Serial Tracking', type: 'REPORT', menuKey: 'inventory.reports.serial-tracking', isDefault: true },
      ],
      menuKeys: [
        'inventory', 'inventory.serials', 'inventory.transactions',
        'inventory.locations', 'inventory.adjustments', 'inventory.reports',
      ],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'marketplace',
      name: 'Marketplace',
      description: 'Browse listings, post offers and jobs, and track applications',
      category: 'MARKETPLACE' as const,
      isCore: false,
      sortOrder: 10,
      iconName: 'shopping-bag',
      dependsOn: [],
      features: [
        { code: 'marketplace_browse', name: 'Browse Marketplace', type: 'PAGE', menuKey: 'marketplace.browse', isDefault: true },
        { code: 'marketplace_post_offer', name: 'Post Offer', type: 'ACTION', menuKey: 'marketplace.post', isDefault: true },
        { code: 'marketplace_post_job', name: 'Post Job', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'marketplace_applications', name: 'Applications', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'marketplace_analytics', name: 'Marketplace Analytics', type: 'REPORT', menuKey: null, isDefault: false },
      ],
      menuKeys: ['marketplace.browse', 'marketplace.post'],
      defaultPricingType: 'PER_USAGE' as const,
      basePrice: 0,
      trialDays: 0,
      usagePricing: { perPromotion: 50, perJobPost: 100 },
    },
  ];

  const moduleMap: Record<string, string> = {};

  for (const mod of moduleDefs) {
    console.log(`  Upserting module: ${mod.code} (${mod.name})`);
    const result = await prisma.moduleDefinition.upsert({
      where: { code: mod.code },
      update: {
        name: mod.name,
        description: mod.description,
        category: mod.category,
        isCore: mod.isCore,
        sortOrder: mod.sortOrder,
        iconName: mod.iconName,
        dependsOn: mod.dependsOn,
        features: mod.features,
        menuKeys: mod.menuKeys,
        defaultPricingType: mod.defaultPricingType,
        basePrice: mod.basePrice,
        priceMonthly: mod.priceMonthly ?? null,
        priceYearly: mod.priceYearly ?? null,
        trialDays: mod.trialDays,
        requiresCredentials: mod.requiresCredentials ?? false,
        usagePricing: mod.usagePricing ?? undefined,
      },
      create: {
        code: mod.code,
        name: mod.name,
        description: mod.description,
        category: mod.category,
        isCore: mod.isCore,
        sortOrder: mod.sortOrder,
        iconName: mod.iconName,
        dependsOn: mod.dependsOn,
        features: mod.features,
        menuKeys: mod.menuKeys,
        defaultPricingType: mod.defaultPricingType,
        basePrice: mod.basePrice,
        priceMonthly: mod.priceMonthly ?? null,
        priceYearly: mod.priceYearly ?? null,
        trialDays: mod.trialDays,
        requiresCredentials: mod.requiresCredentials ?? false,
        usagePricing: mod.usagePricing ? (mod.usagePricing as any) : undefined,
      },
    });
    moduleMap[mod.code] = result.id;
  }

  console.log(`  Seeded ${moduleDefs.length} modules.`);

  // ── 2. Subscription Packages ───────────────────────────────────────

  const packages = [
    {
      packageCode: 'free',
      packageName: 'Free',
      tagline: 'Get started at no cost',
      description: 'Basic CRM features for small teams',
      tier: 0,
      priceMonthlyInr: 0,
      priceYearlyInr: 0,
      yearlyDiscountPct: 0,
      trialDays: 0,
      entityLimits: {
        CONTACTS: { limit: 50, extraPricePerUnit: 0 },
        ORGANIZATIONS: { limit: 20, extraPricePerUnit: 0 },
        LEADS: { limit: 50, extraPricePerUnit: 0 },
        PRODUCTS: { limit: 20, extraPricePerUnit: 0 },
        USERS: { limit: 2, extraPricePerUnit: 0 },
        QUOTATIONS: { limit: 10, extraPricePerUnit: 0 },
        INVOICES: { limit: 10, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: false,
      isPopular: false,
      badgeText: null,
      color: '#6B7280',
    },
    {
      packageCode: 'starter',
      packageName: 'Starter Pack',
      tagline: 'Everything you need to grow',
      description: 'Enhanced CRM with more capacity and integrations',
      tier: 1,
      priceMonthlyInr: 999,
      priceYearlyInr: 9990,
      yearlyDiscountPct: 17,
      trialDays: 14,
      entityLimits: {
        CONTACTS: { limit: 500, extraPricePerUnit: 5 },
        ORGANIZATIONS: { limit: 100, extraPricePerUnit: 0 },
        LEADS: { limit: 1000, extraPricePerUnit: 10 },
        QUOTATIONS: { limit: 200, extraPricePerUnit: 0 },
        INVOICES: { limit: 200, extraPricePerUnit: 0 },
        PRODUCTS: { limit: 500, extraPricePerUnit: 0 },
        USERS: { limit: 5, extraPricePerUnit: 200 },
        FILE_STORAGE_MB: { limit: 1024, extraPricePerUnit: 0 },
        DB_SIZE_MB: { limit: 512, extraPricePerUnit: 0 },
        EMAIL_PER_MONTH: { limit: 1000, extraPricePerUnit: 0 },
        WORKFLOWS: { limit: 10, extraPricePerUnit: 0 },
        CUSTOM_FIELDS: { limit: 20, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: false,
      isPopular: false,
      badgeText: null,
      color: '#3B82F6',
    },
    {
      packageCode: 'professional',
      packageName: 'Professional',
      tagline: 'For growing businesses',
      description: 'Full-featured CRM with advanced analytics and integrations',
      tier: 2,
      priceMonthlyInr: 2999,
      priceYearlyInr: 29990,
      yearlyDiscountPct: 17,
      trialDays: 14,
      entityLimits: {
        CONTACTS: { limit: 5000, extraPricePerUnit: 3 },
        ORGANIZATIONS: { limit: 1000, extraPricePerUnit: 0 },
        LEADS: { limit: -1, extraPricePerUnit: 0 },
        QUOTATIONS: { limit: 1000, extraPricePerUnit: 0 },
        INVOICES: { limit: 1000, extraPricePerUnit: 0 },
        PRODUCTS: { limit: 2000, extraPricePerUnit: 0 },
        USERS: { limit: 25, extraPricePerUnit: 150 },
        FILE_STORAGE_MB: { limit: 5120, extraPricePerUnit: 0 },
        DB_SIZE_MB: { limit: 2048, extraPricePerUnit: 0 },
        MARKETPLACE_PROMOTIONS: { limit: 20, extraPricePerUnit: 0 },
        EMAIL_PER_MONTH: { limit: 5000, extraPricePerUnit: 0 },
        WHATSAPP_PER_MONTH: { limit: 1000, extraPricePerUnit: 0 },
        API_CALLS_PER_DAY: { limit: 10000, extraPricePerUnit: 0 },
        REPORTS: { limit: -1, extraPricePerUnit: 0 },
        WORKFLOWS: { limit: 50, extraPricePerUnit: 0 },
        CUSTOM_FIELDS: { limit: 100, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: true,
      isPopular: true,
      badgeText: 'Most Popular',
      color: '#8B5CF6',
    },
    {
      packageCode: 'enterprise',
      packageName: 'Enterprise',
      tagline: 'Unlimited power for large teams',
      description: 'Enterprise-grade CRM with unlimited everything and dedicated support',
      tier: 3,
      priceMonthlyInr: 9999,
      priceYearlyInr: 99990,
      yearlyDiscountPct: 17,
      trialDays: 30,
      entityLimits: {
        CONTACTS: { limit: -1, extraPricePerUnit: 0 },
        ORGANIZATIONS: { limit: -1, extraPricePerUnit: 0 },
        LEADS: { limit: -1, extraPricePerUnit: 0 },
        QUOTATIONS: { limit: -1, extraPricePerUnit: 0 },
        INVOICES: { limit: -1, extraPricePerUnit: 0 },
        PRODUCTS: { limit: -1, extraPricePerUnit: 0 },
        USERS: { limit: -1, extraPricePerUnit: 0 },
        FILE_STORAGE_MB: { limit: -1, extraPricePerUnit: 0 },
        DB_SIZE_MB: { limit: -1, extraPricePerUnit: 0 },
        MARKETPLACE_PROMOTIONS: { limit: -1, extraPricePerUnit: 0 },
        EMAIL_PER_MONTH: { limit: -1, extraPricePerUnit: 0 },
        WHATSAPP_PER_MONTH: { limit: -1, extraPricePerUnit: 0 },
        API_CALLS_PER_DAY: { limit: -1, extraPricePerUnit: 0 },
        REPORTS: { limit: -1, extraPricePerUnit: 0 },
        WORKFLOWS: { limit: -1, extraPricePerUnit: 0 },
        CUSTOM_FIELDS: { limit: -1, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: true,
      maxDbSizeMb: 10240,
      isPopular: false,
      badgeText: 'Best Value',
      color: '#F59E0B',
    },
  ];

  const packageMap: Record<string, string> = {};

  for (const pkg of packages) {
    console.log(`  Upserting package: ${pkg.packageCode} (${pkg.packageName})`);
    const result = await prisma.subscriptionPackage.upsert({
      where: { packageCode: pkg.packageCode },
      update: {
        packageName: pkg.packageName,
        tagline: pkg.tagline,
        description: pkg.description,
        tier: pkg.tier,
        priceMonthlyInr: pkg.priceMonthlyInr,
        priceYearlyInr: pkg.priceYearlyInr,
        yearlyDiscountPct: pkg.yearlyDiscountPct,
        trialDays: pkg.trialDays,
        entityLimits: pkg.entityLimits,
        hasDedicatedDb: pkg.hasDedicatedDb,
        maxDbSizeMb: pkg.maxDbSizeMb ?? null,
        isPopular: pkg.isPopular,
        badgeText: pkg.badgeText,
        color: pkg.color,
      },
      create: {
        packageCode: pkg.packageCode,
        packageName: pkg.packageName,
        tagline: pkg.tagline,
        description: pkg.description,
        tier: pkg.tier,
        priceMonthlyInr: pkg.priceMonthlyInr,
        priceYearlyInr: pkg.priceYearlyInr,
        yearlyDiscountPct: pkg.yearlyDiscountPct,
        trialDays: pkg.trialDays,
        entityLimits: pkg.entityLimits,
        hasDedicatedDb: pkg.hasDedicatedDb,
        maxDbSizeMb: pkg.maxDbSizeMb ?? null,
        isPopular: pkg.isPopular,
        badgeText: pkg.badgeText,
        color: pkg.color,
      },
    });
    packageMap[pkg.packageCode] = result.id;
  }

  console.log(`  Seeded ${packages.length} packages.`);

  // ── 3. Package-Module Links ────────────────────────────────────────

  interface PackageModuleLink {
    packageCode: string;
    moduleCode: string;
    pricingType: 'FREE' | 'INCLUDED' | 'ADDON' | 'PER_USAGE';
    addonPrice?: number;
    disabledFeatures?: string[];
    sortOrder: number;
  }

  const packageModuleLinks: PackageModuleLink[] = [
    // ── Free ──
    { packageCode: 'free', moduleCode: 'contacts', pricingType: 'FREE', sortOrder: 1 },
    { packageCode: 'free', moduleCode: 'leads', pricingType: 'FREE', disabledFeatures: ['lead_scoring', 'lead_pipeline'], sortOrder: 2 },
    { packageCode: 'free', moduleCode: 'products', pricingType: 'FREE', sortOrder: 3 },

    // ── Starter ──
    { packageCode: 'starter', moduleCode: 'contacts', pricingType: 'INCLUDED', sortOrder: 1 },
    { packageCode: 'starter', moduleCode: 'leads', pricingType: 'INCLUDED', sortOrder: 2 },
    { packageCode: 'starter', moduleCode: 'products', pricingType: 'INCLUDED', sortOrder: 3 },
    { packageCode: 'starter', moduleCode: 'quotations', pricingType: 'INCLUDED', sortOrder: 4 },
    { packageCode: 'starter', moduleCode: 'tasks', pricingType: 'INCLUDED', sortOrder: 5 },

    // ── Professional ──
    { packageCode: 'professional', moduleCode: 'contacts', pricingType: 'INCLUDED', sortOrder: 1 },
    { packageCode: 'professional', moduleCode: 'leads', pricingType: 'INCLUDED', sortOrder: 2 },
    { packageCode: 'professional', moduleCode: 'products', pricingType: 'INCLUDED', sortOrder: 3 },
    { packageCode: 'professional', moduleCode: 'quotations', pricingType: 'INCLUDED', sortOrder: 4 },
    { packageCode: 'professional', moduleCode: 'invoices', pricingType: 'INCLUDED', sortOrder: 5 },
    { packageCode: 'professional', moduleCode: 'payments', pricingType: 'INCLUDED', sortOrder: 6 },
    { packageCode: 'professional', moduleCode: 'whatsapp', pricingType: 'ADDON', addonPrice: 499, sortOrder: 7 },
    { packageCode: 'professional', moduleCode: 'tasks', pricingType: 'INCLUDED', sortOrder: 8 },
    { packageCode: 'professional', moduleCode: 'reports', pricingType: 'INCLUDED', sortOrder: 9 },
    { packageCode: 'professional', moduleCode: 'marketplace', pricingType: 'PER_USAGE', sortOrder: 10 },
    { packageCode: 'professional', moduleCode: 'inventory', pricingType: 'INCLUDED', sortOrder: 11 },

    // ── Enterprise ──
    { packageCode: 'enterprise', moduleCode: 'contacts', pricingType: 'INCLUDED', sortOrder: 1 },
    { packageCode: 'enterprise', moduleCode: 'leads', pricingType: 'INCLUDED', sortOrder: 2 },
    { packageCode: 'enterprise', moduleCode: 'products', pricingType: 'INCLUDED', sortOrder: 3 },
    { packageCode: 'enterprise', moduleCode: 'quotations', pricingType: 'INCLUDED', sortOrder: 4 },
    { packageCode: 'enterprise', moduleCode: 'invoices', pricingType: 'INCLUDED', sortOrder: 5 },
    { packageCode: 'enterprise', moduleCode: 'payments', pricingType: 'INCLUDED', sortOrder: 6 },
    { packageCode: 'enterprise', moduleCode: 'whatsapp', pricingType: 'INCLUDED', sortOrder: 7 },
    { packageCode: 'enterprise', moduleCode: 'tasks', pricingType: 'INCLUDED', sortOrder: 8 },
    { packageCode: 'enterprise', moduleCode: 'reports', pricingType: 'INCLUDED', sortOrder: 9 },
    { packageCode: 'enterprise', moduleCode: 'marketplace', pricingType: 'INCLUDED', sortOrder: 10 },
    { packageCode: 'enterprise', moduleCode: 'inventory', pricingType: 'INCLUDED', sortOrder: 11 },
  ];

  let linkCount = 0;
  for (const link of packageModuleLinks) {
    const packageId = packageMap[link.packageCode];
    const moduleId = moduleMap[link.moduleCode];

    if (!packageId || !moduleId) {
      console.warn(`  SKIP: package=${link.packageCode} or module=${link.moduleCode} not found`);
      continue;
    }

    console.log(`  Linking ${link.packageCode} → ${link.moduleCode} (${link.pricingType})`);
    await prisma.packageModule.upsert({
      where: {
        packageId_moduleId: { packageId, moduleId },
      },
      update: {
        pricingType: link.pricingType,
        addonPrice: link.addonPrice ?? null,
        disabledFeatures: link.disabledFeatures ?? [],
        sortOrder: link.sortOrder,
      },
      create: {
        packageId,
        moduleId,
        pricingType: link.pricingType,
        addonPrice: link.addonPrice ?? null,
        disabledFeatures: link.disabledFeatures ?? [],
        sortOrder: link.sortOrder,
      },
    });
    linkCount++;
  }

  console.log(`  Linked ${linkCount} package-module pairs.`);
  console.log('--- Modules & Packages seeding complete ---');
}
