export class UpdateListingCommand {
  constructor(
    public readonly id: string,
    public readonly tenantId: string,
    public readonly updatedById: string,
    public readonly title?: string,
    public readonly description?: string,
    public readonly shortDescription?: string,
    public readonly categoryId?: string,
    public readonly subcategoryId?: string,
    public readonly mediaUrls?: any[],
    public readonly basePrice?: number,
    public readonly mrp?: number,
    public readonly minOrderQty?: number,
    public readonly maxOrderQty?: number,
    public readonly hsnCode?: string,
    public readonly gstRate?: number,
    public readonly stockAvailable?: number,
    public readonly visibility?: string,
    public readonly visibilityConfig?: Record<string, unknown>,
    public readonly publishAt?: Date,
    public readonly expiresAt?: Date,
    public readonly attributes?: Record<string, any>,
    public readonly keywords?: string[],
    public readonly shippingConfig?: Record<string, unknown>,
    public readonly requirementConfig?: Record<string, unknown>,
  ) {}
}
