import { PrismaClient } from '@prisma/client';

export async function seedModulesAndPackages(prisma: PrismaClient) {
  console.log('--- Seeding Modules & Packages ---');

  // ── 1. Module Definitions ──────────────────────────────────────────

  const moduleDefs = [
    {
      code: 'CONTACTS',
      name: 'Contact Management',
      description: 'Manage contacts, import/export, and contact dashboards',
      category: 'CORE' as const,
      isCore: true,
      sortOrder: 1,
      iconName: 'contact',
      dependsOn: [],
      features: [
        { code: 'CONTACT_LIST', name: 'Contact List', type: 'PAGE', menuKey: 'crm.contacts', isDefault: true },
        { code: 'CONTACT_CREATE', name: 'Create Contact', type: 'PAGE', menuKey: 'crm.contacts.create', isDefault: true },
        { code: 'CONTACT_EDIT', name: 'Edit Contact', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'CONTACT_DETAIL', name: 'Contact Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'CONTACT_IMPORT', name: 'Bulk Import Contacts', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'CONTACT_EXPORT', name: 'Export Contacts', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'CONTACT_DASHBOARD', name: 'Contact Dashboard', type: 'WIDGET', menuKey: 'crm.contacts.dashboard', isDefault: false },
        { code: 'CONTACT_REPORT', name: 'Contact Report', type: 'REPORT', menuKey: 'reports.contacts', isDefault: true },
      ],
      menuKeys: ['crm.contacts', 'crm.contacts.create', 'crm.contacts.dashboard', 'reports.contacts'],
      defaultPricingType: 'FREE' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'LEADS',
      name: 'Lead Management',
      description: 'Track leads through pipeline stages with scoring and kanban views',
      category: 'CRM' as const,
      isCore: false,
      sortOrder: 2,
      iconName: 'target',
      dependsOn: ['CONTACTS'],
      features: [
        { code: 'LEAD_LIST', name: 'Lead List', type: 'PAGE', menuKey: 'crm.leads', isDefault: true },
        { code: 'LEAD_CREATE', name: 'Create Lead', type: 'PAGE', menuKey: 'crm.leads.create', isDefault: true },
        { code: 'LEAD_EDIT', name: 'Edit Lead', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'LEAD_DETAIL', name: 'Lead Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'LEAD_PIPELINE', name: 'Lead Pipeline', type: 'PAGE', menuKey: 'crm.leads.pipeline', isDefault: true },
        { code: 'LEAD_KANBAN', name: 'Lead Kanban', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'LEAD_SCORING', name: 'Lead Scoring', type: 'ACTION', menuKey: null, isDefault: false },
        { code: 'LEAD_IMPORT', name: 'Bulk Import Leads', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'LEAD_REPORT', name: 'Lead Report', type: 'REPORT', menuKey: 'reports.leads', isDefault: true },
      ],
      menuKeys: ['crm.leads', 'crm.leads.create', 'crm.leads.pipeline', 'reports.leads'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'PRODUCTS',
      name: 'Product Catalog',
      description: 'Manage products, categories, brands, and pricing',
      category: 'CORE' as const,
      isCore: true,
      sortOrder: 3,
      iconName: 'package',
      dependsOn: [],
      features: [
        { code: 'PRODUCT_LIST', name: 'Product List', type: 'PAGE', menuKey: 'crm.products', isDefault: true },
        { code: 'PRODUCT_CREATE', name: 'Create Product', type: 'PAGE', menuKey: 'crm.products.create', isDefault: true },
        { code: 'PRODUCT_EDIT', name: 'Edit Product', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'PRODUCT_DETAIL', name: 'Product Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'PRODUCT_CATEGORIES', name: 'Product Categories', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'PRODUCT_BRANDS', name: 'Product Brands', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'PRODUCT_PRICING', name: 'Product Pricing', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'PRODUCT_IMPORT', name: 'Bulk Import Products', type: 'ACTION', menuKey: null, isDefault: true },
      ],
      menuKeys: ['crm.products', 'crm.products.create'],
      defaultPricingType: 'FREE' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'QUOTATIONS',
      name: 'Quotation Management',
      description: 'Create and manage quotations with revision tracking and approvals',
      category: 'SALES' as const,
      isCore: false,
      sortOrder: 4,
      iconName: 'file-text',
      dependsOn: ['CONTACTS', 'PRODUCTS'],
      features: [
        { code: 'QUOTATION_LIST', name: 'Quotation List', type: 'PAGE', menuKey: 'crm.quotations', isDefault: true },
        { code: 'QUOTATION_CREATE', name: 'Create Quotation', type: 'PAGE', menuKey: 'crm.quotations.create', isDefault: true },
        { code: 'QUOTATION_EDIT', name: 'Edit Quotation', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'QUOTATION_DETAIL', name: 'Quotation Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'QUOTATION_REVISE', name: 'Revise Quotation', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'QUOTATION_APPROVE', name: 'Approve Quotation', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'QUOTATION_PDF', name: 'Quotation PDF', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'QUOTATION_REPORT', name: 'Quotation Report', type: 'REPORT', menuKey: 'reports.quotations', isDefault: true },
      ],
      menuKeys: ['crm.quotations', 'crm.quotations.create', 'reports.quotations'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'INVOICES',
      name: 'Invoice Management',
      description: 'Generate invoices with GST calculations and payment links',
      category: 'FINANCE' as const,
      isCore: false,
      sortOrder: 5,
      iconName: 'receipt',
      dependsOn: ['QUOTATIONS'],
      features: [
        { code: 'INVOICE_LIST', name: 'Invoice List', type: 'PAGE', menuKey: 'finance.invoices', isDefault: true },
        { code: 'INVOICE_CREATE', name: 'Create Invoice', type: 'PAGE', menuKey: 'finance.invoices.create', isDefault: true },
        { code: 'INVOICE_EDIT', name: 'Edit Invoice', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'INVOICE_DETAIL', name: 'Invoice Detail', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'INVOICE_GST_CALC', name: 'GST Calculator', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'INVOICE_PDF', name: 'Invoice PDF', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'INVOICE_PAYMENT_LINK', name: 'Payment Link', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'INVOICE_REPORT', name: 'Invoice Report', type: 'REPORT', menuKey: 'reports.invoices', isDefault: true },
      ],
      menuKeys: ['finance.invoices', 'finance.invoices.create', 'reports.invoices'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'PAYMENTS',
      name: 'Payment Collection',
      description: 'Record payments, integrate Razorpay, and generate receipts',
      category: 'FINANCE' as const,
      isCore: false,
      sortOrder: 6,
      iconName: 'credit-card',
      dependsOn: ['INVOICES'],
      features: [
        { code: 'PAYMENT_LIST', name: 'Payment List', type: 'PAGE', menuKey: 'finance.payments', isDefault: true },
        { code: 'PAYMENT_RECORD', name: 'Record Payment', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'PAYMENT_RAZORPAY', name: 'Razorpay Integration', type: 'INTEGRATION', menuKey: null, isDefault: true },
        { code: 'PAYMENT_RECEIPT', name: 'Receipt Generation', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'PAYMENT_REPORT', name: 'Payment Report', type: 'REPORT', menuKey: 'reports.payments', isDefault: true },
      ],
      menuKeys: ['finance.payments', 'reports.payments'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'WHATSAPP',
      name: 'WhatsApp Integration',
      description: 'Send messages, manage templates, chatbot, and broadcast',
      category: 'COMMUNICATION' as const,
      isCore: false,
      sortOrder: 7,
      iconName: 'message-circle',
      dependsOn: [],
      features: [
        { code: 'WHATSAPP_TEMPLATES', name: 'WhatsApp Templates', type: 'PAGE', menuKey: 'communication.whatsapp', isDefault: true },
        { code: 'WHATSAPP_SEND', name: 'Send Message', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'WHATSAPP_CHATBOT', name: 'Chatbot', type: 'ACTION', menuKey: null, isDefault: false },
        { code: 'WHATSAPP_BROADCAST', name: 'Broadcast', type: 'ACTION', menuKey: null, isDefault: false },
        { code: 'WHATSAPP_REPORT', name: 'WhatsApp Report', type: 'REPORT', menuKey: null, isDefault: true },
      ],
      menuKeys: ['communication.whatsapp'],
      defaultPricingType: 'ADDON' as const,
      basePrice: 499,
      priceMonthly: 499,
      priceYearly: 4990,
      trialDays: 14,
      requiresCredentials: true,
    },
    {
      code: 'TASKS',
      name: 'Task Management',
      description: 'Create and track tasks with calendar and reminder support',
      category: 'OPERATIONS' as const,
      isCore: false,
      sortOrder: 8,
      iconName: 'check-square',
      dependsOn: [],
      features: [
        { code: 'TASK_LIST', name: 'Task List', type: 'PAGE', menuKey: 'operations.tasks', isDefault: true },
        { code: 'TASK_CREATE', name: 'Create Task', type: 'PAGE', menuKey: 'operations.tasks.create', isDefault: true },
        { code: 'TASK_EDIT', name: 'Edit Task', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'TASK_CALENDAR', name: 'Task Calendar', type: 'PAGE', menuKey: 'operations.calendar', isDefault: true },
        { code: 'TASK_REMINDERS', name: 'Task Reminders', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'TASK_REPORT', name: 'Task Report', type: 'REPORT', menuKey: null, isDefault: true },
      ],
      menuKeys: ['operations.tasks', 'operations.tasks.create', 'operations.calendar'],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'REPORTS',
      name: 'Advanced Reports',
      description: 'Build custom reports, schedule exports, and view dashboards',
      category: 'ANALYTICS' as const,
      isCore: false,
      sortOrder: 9,
      iconName: 'bar-chart-2',
      dependsOn: [],
      features: [
        { code: 'REPORT_BUILDER', name: 'Report Builder', type: 'PAGE', menuKey: 'reports.builder', isDefault: true },
        { code: 'REPORT_SCHEDULED', name: 'Scheduled Reports', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'REPORT_EXPORT', name: 'Report Export', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'REPORT_DASHBOARD', name: 'Report Dashboard', type: 'PAGE', menuKey: 'reports.dashboard', isDefault: true },
        { code: 'REPORT_CUSTOM', name: 'Custom Reports', type: 'REPORT', menuKey: null, isDefault: false },
      ],
      menuKeys: ['reports.builder', 'reports.dashboard'],
      defaultPricingType: 'ADDON' as const,
      basePrice: 299,
      priceMonthly: 299,
      priceYearly: 2990,
      trialDays: 7,
    },
    {
      code: 'INVENTORY',
      name: 'Inventory Management',
      description: 'Serial tracking, stock in/out, locations, adjustments, and reports',
      category: 'OPERATIONS' as const,
      isCore: false,
      sortOrder: 11,
      iconName: 'warehouse',
      dependsOn: ['PRODUCTS'],
      features: [
        { code: 'INVENTORY_DASHBOARD', name: 'Inventory Dashboard', type: 'PAGE', menuKey: 'inventory.dashboard', isDefault: true },
        { code: 'SERIAL_LIST', name: 'Serial / Key List', type: 'PAGE', menuKey: 'inventory.serials', isDefault: true },
        { code: 'SERIAL_CREATE', name: 'Add Serial / Key', type: 'PAGE', menuKey: 'inventory.serials.new', isDefault: true },
        { code: 'SERIAL_BULK_IMPORT', name: 'Bulk Import Serials', type: 'ACTION', menuKey: 'inventory.serials.bulk-import', isDefault: true },
        { code: 'STOCK_TRANSACTIONS', name: 'Stock Transactions', type: 'PAGE', menuKey: 'inventory.transactions', isDefault: true },
        { code: 'STOCK_LOCATIONS', name: 'Stock Locations', type: 'PAGE', menuKey: 'inventory.locations', isDefault: true },
        { code: 'STOCK_ADJUSTMENTS', name: 'Stock Adjustments', type: 'PAGE', menuKey: 'inventory.adjustments', isDefault: true },
        { code: 'INVENTORY_REPORTS', name: 'Inventory Reports', type: 'REPORT', menuKey: 'inventory.reports', isDefault: true },
        { code: 'STOCK_LEDGER', name: 'Stock Ledger', type: 'REPORT', menuKey: 'inventory.reports.ledger', isDefault: true },
        { code: 'EXPIRY_REPORT', name: 'Expiry Report', type: 'REPORT', menuKey: 'inventory.reports.expiry', isDefault: true },
        { code: 'VALUATION_REPORT', name: 'Stock Valuation', type: 'REPORT', menuKey: 'inventory.reports.valuation', isDefault: true },
        { code: 'SERIAL_TRACKING', name: 'Serial Tracking', type: 'REPORT', menuKey: 'inventory.reports.serial-tracking', isDefault: true },
      ],
      menuKeys: [
        'inventory', 'inventory.serials', 'inventory.transactions',
        'inventory.locations', 'inventory.adjustments', 'inventory.reports',
      ],
      defaultPricingType: 'INCLUDED' as const,
      basePrice: 0,
      trialDays: 0,
    },
    {
      code: 'MARKETPLACE',
      name: 'Marketplace',
      description: 'Browse listings, post offers and jobs, and track applications',
      category: 'MARKETPLACE' as const,
      isCore: false,
      sortOrder: 10,
      iconName: 'shopping-bag',
      dependsOn: [],
      features: [
        { code: 'MARKETPLACE_BROWSE', name: 'Browse Marketplace', type: 'PAGE', menuKey: 'marketplace.browse', isDefault: true },
        { code: 'MARKETPLACE_POST_OFFER', name: 'Post Offer', type: 'ACTION', menuKey: 'marketplace.post', isDefault: true },
        { code: 'MARKETPLACE_POST_JOB', name: 'Post Job', type: 'ACTION', menuKey: null, isDefault: true },
        { code: 'MARKETPLACE_APPLICATIONS', name: 'Applications', type: 'PAGE', menuKey: null, isDefault: true },
        { code: 'MARKETPLACE_ANALYTICS', name: 'Marketplace Analytics', type: 'REPORT', menuKey: null, isDefault: false },
      ],
      menuKeys: ['marketplace.browse', 'marketplace.post'],
      defaultPricingType: 'PER_USAGE' as const,
      basePrice: 0,
      trialDays: 0,
      usagePricing: { perPromotion: 50, perJobPost: 100 },
    },
  ];

  const moduleMap: Record<string, string> = {};

  for (const mod of moduleDefs) {
    console.log(`  Upserting module: ${mod.code} (${mod.name})`);
    const result = await prisma.moduleDefinition.upsert({
      where: { code: mod.code },
      update: {
        name: mod.name,
        description: mod.description,
        category: mod.category,
        isCore: mod.isCore,
        sortOrder: mod.sortOrder,
        iconName: mod.iconName,
        dependsOn: mod.dependsOn,
        features: mod.features,
        menuKeys: mod.menuKeys,
        defaultPricingType: mod.defaultPricingType,
        basePrice: mod.basePrice,
        priceMonthly: mod.priceMonthly ?? null,
        priceYearly: mod.priceYearly ?? null,
        trialDays: mod.trialDays,
        requiresCredentials: mod.requiresCredentials ?? false,
        usagePricing: mod.usagePricing ?? undefined,
      },
      create: {
        code: mod.code,
        name: mod.name,
        description: mod.description,
        category: mod.category,
        isCore: mod.isCore,
        sortOrder: mod.sortOrder,
        iconName: mod.iconName,
        dependsOn: mod.dependsOn,
        features: mod.features,
        menuKeys: mod.menuKeys,
        defaultPricingType: mod.defaultPricingType,
        basePrice: mod.basePrice,
        priceMonthly: mod.priceMonthly ?? null,
        priceYearly: mod.priceYearly ?? null,
        trialDays: mod.trialDays,
        requiresCredentials: mod.requiresCredentials ?? false,
        usagePricing: mod.usagePricing ? (mod.usagePricing as any) : undefined,
      },
    });
    moduleMap[mod.code] = result.id;
  }

  console.log(`  Seeded ${moduleDefs.length} modules.`);

  // ── 2. Subscription Packages ───────────────────────────────────────

  const packages = [
    {
      packageCode: 'FREE',
      packageName: 'Free',
      tagline: 'Get started at no cost',
      description: 'Basic CRM features for small teams',
      tier: 0,
      priceMonthlyInr: 0,
      priceYearlyInr: 0,
      yearlyDiscountPct: 0,
      trialDays: 0,
      entityLimits: {
        CONTACTS: { limit: 50, extraPricePerUnit: 0 },
        ORGANIZATIONS: { limit: 20, extraPricePerUnit: 0 },
        LEADS: { limit: 50, extraPricePerUnit: 0 },
        PRODUCTS: { limit: 20, extraPricePerUnit: 0 },
        USERS: { limit: 2, extraPricePerUnit: 0 },
        QUOTATIONS: { limit: 10, extraPricePerUnit: 0 },
        INVOICES: { limit: 10, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: false,
      isPopular: false,
      badgeText: null,
      color: '#6B7280',
    },
    {
      packageCode: 'STARTER',
      packageName: 'Starter Pack',
      tagline: 'Everything you need to grow',
      description: 'Enhanced CRM with more capacity and integrations',
      tier: 1,
      priceMonthlyInr: 999,
      priceYearlyInr: 9990,
      yearlyDiscountPct: 17,
      trialDays: 14,
      entityLimits: {
        CONTACTS: { limit: 500, extraPricePerUnit: 5 },
        ORGANIZATIONS: { limit: 100, extraPricePerUnit: 0 },
        LEADS: { limit: 1000, extraPricePerUnit: 10 },
        QUOTATIONS: { limit: 200, extraPricePerUnit: 0 },
        INVOICES: { limit: 200, extraPricePerUnit: 0 },
        PRODUCTS: { limit: 500, extraPricePerUnit: 0 },
        USERS: { limit: 5, extraPricePerUnit: 200 },
        FILE_STORAGE_MB: { limit: 1024, extraPricePerUnit: 0 },
        DB_SIZE_MB: { limit: 512, extraPricePerUnit: 0 },
        EMAIL_PER_MONTH: { limit: 1000, extraPricePerUnit: 0 },
        WORKFLOWS: { limit: 10, extraPricePerUnit: 0 },
        CUSTOM_FIELDS: { limit: 20, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: false,
      isPopular: false,
      badgeText: null,
      color: '#3B82F6',
    },
    {
      packageCode: 'PROFESSIONAL',
      packageName: 'Professional',
      tagline: 'For growing businesses',
      description: 'Full-featured CRM with advanced analytics and integrations',
      tier: 2,
      priceMonthlyInr: 2999,
      priceYearlyInr: 29990,
      yearlyDiscountPct: 17,
      trialDays: 14,
      entityLimits: {
        CONTACTS: { limit: 5000, extraPricePerUnit: 3 },
        ORGANIZATIONS: { limit: 1000, extraPricePerUnit: 0 },
        LEADS: { limit: -1, extraPricePerUnit: 0 },
        QUOTATIONS: { limit: 1000, extraPricePerUnit: 0 },
        INVOICES: { limit: 1000, extraPricePerUnit: 0 },
        PRODUCTS: { limit: 2000, extraPricePerUnit: 0 },
        USERS: { limit: 25, extraPricePerUnit: 150 },
        FILE_STORAGE_MB: { limit: 5120, extraPricePerUnit: 0 },
        DB_SIZE_MB: { limit: 2048, extraPricePerUnit: 0 },
        MARKETPLACE_PROMOTIONS: { limit: 20, extraPricePerUnit: 0 },
        EMAIL_PER_MONTH: { limit: 5000, extraPricePerUnit: 0 },
        WHATSAPP_PER_MONTH: { limit: 1000, extraPricePerUnit: 0 },
        API_CALLS_PER_DAY: { limit: 10000, extraPricePerUnit: 0 },
        REPORTS: { limit: -1, extraPricePerUnit: 0 },
        WORKFLOWS: { limit: 50, extraPricePerUnit: 0 },
        CUSTOM_FIELDS: { limit: 100, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: true,
      isPopular: true,
      badgeText: 'Most Popular',
      color: '#8B5CF6',
    },
    {
      packageCode: 'ENTERPRISE',
      packageName: 'Enterprise',
      tagline: 'Unlimited power for large teams',
      description: 'Enterprise-grade CRM with unlimited everything and dedicated support',
      tier: 3,
      priceMonthlyInr: 9999,
      priceYearlyInr: 99990,
      yearlyDiscountPct: 17,
      trialDays: 30,
      entityLimits: {
        CONTACTS: { limit: -1, extraPricePerUnit: 0 },
        ORGANIZATIONS: { limit: -1, extraPricePerUnit: 0 },
        LEADS: { limit: -1, extraPricePerUnit: 0 },
        QUOTATIONS: { limit: -1, extraPricePerUnit: 0 },
        INVOICES: { limit: -1, extraPricePerUnit: 0 },
        PRODUCTS: { limit: -1, extraPricePerUnit: 0 },
        USERS: { limit: -1, extraPricePerUnit: 0 },
        FILE_STORAGE_MB: { limit: -1, extraPricePerUnit: 0 },
        DB_SIZE_MB: { limit: -1, extraPricePerUnit: 0 },
        MARKETPLACE_PROMOTIONS: { limit: -1, extraPricePerUnit: 0 },
        EMAIL_PER_MONTH: { limit: -1, extraPricePerUnit: 0 },
        WHATSAPP_PER_MONTH: { limit: -1, extraPricePerUnit: 0 },
        API_CALLS_PER_DAY: { limit: -1, extraPricePerUnit: 0 },
        REPORTS: { limit: -1, extraPricePerUnit: 0 },
        WORKFLOWS: { limit: -1, extraPricePerUnit: 0 },
        CUSTOM_FIELDS: { limit: -1, extraPricePerUnit: 0 },
      },
      hasDedicatedDb: true,
      maxDbSizeMb: 10240,
      isPopular: false,
      badgeText: 'Best Value',
      color: '#F59E0B',
    },
  ];

  const packageMap: Record<string, string> = {};

  for (const pkg of packages) {
    console.log(`  Upserting package: ${pkg.packageCode} (${pkg.packageName})`);
    const result = await prisma.subscriptionPackage.upsert({
      where: { packageCode: pkg.packageCode },
      update: {
        packageName: pkg.packageName,
        tagline: pkg.tagline,
        description: pkg.description,
        tier: pkg.tier,
        priceMonthlyInr: pkg.priceMonthlyInr,
        priceYearlyInr: pkg.priceYearlyInr,
        yearlyDiscountPct: pkg.yearlyDiscountPct,
        trialDays: pkg.trialDays,
        entityLimits: pkg.entityLimits,
        hasDedicatedDb: pkg.hasDedicatedDb,
        maxDbSizeMb: pkg.maxDbSizeMb ?? null,
        isPopular: pkg.isPopular,
        badgeText: pkg.badgeText,
        color: pkg.color,
      },
      create: {
        packageCode: pkg.packageCode,
        packageName: pkg.packageName,
        tagline: pkg.tagline,
        description: pkg.description,
        tier: pkg.tier,
        priceMonthlyInr: pkg.priceMonthlyInr,
        priceYearlyInr: pkg.priceYearlyInr,
        yearlyDiscountPct: pkg.yearlyDiscountPct,
        trialDays: pkg.trialDays,
        entityLimits: pkg.entityLimits,
        hasDedicatedDb: pkg.hasDedicatedDb,
        maxDbSizeMb: pkg.maxDbSizeMb ?? null,
        isPopular: pkg.isPopular,
        badgeText: pkg.badgeText,
        color: pkg.color,
      },
    });
    packageMap[pkg.packageCode] = result.id;
  }

  console.log(`  Seeded ${packages.length} packages.`);

  // ── 3. Package-Module Links ────────────────────────────────────────

  interface PackageModuleLink {
    packageCode: string;
    moduleCode: string;
    pricingType: 'FREE' | 'INCLUDED' | 'ADDON' | 'PER_USAGE';
    addonPrice?: number;
    disabledFeatures?: string[];
    sortOrder: number;
  }

  const packageModuleLinks: PackageModuleLink[] = [
    // ── Free ──
    { packageCode: 'FREE', moduleCode: 'CONTACTS', pricingType: 'FREE', sortOrder: 1 },
    { packageCode: 'FREE', moduleCode: 'LEADS', pricingType: 'FREE', disabledFeatures: ['LEAD_SCORING', 'LEAD_PIPELINE'], sortOrder: 2 },
    { packageCode: 'FREE', moduleCode: 'PRODUCTS', pricingType: 'FREE', sortOrder: 3 },

    // ── Starter ──
    { packageCode: 'STARTER', moduleCode: 'CONTACTS', pricingType: 'INCLUDED', sortOrder: 1 },
    { packageCode: 'STARTER', moduleCode: 'LEADS', pricingType: 'INCLUDED', sortOrder: 2 },
    { packageCode: 'STARTER', moduleCode: 'PRODUCTS', pricingType: 'INCLUDED', sortOrder: 3 },
    { packageCode: 'STARTER', moduleCode: 'QUOTATIONS', pricingType: 'INCLUDED', sortOrder: 4 },
    { packageCode: 'STARTER', moduleCode: 'TASKS', pricingType: 'INCLUDED', sortOrder: 5 },

    // ── Professional ──
    { packageCode: 'PROFESSIONAL', moduleCode: 'CONTACTS', pricingType: 'INCLUDED', sortOrder: 1 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'LEADS', pricingType: 'INCLUDED', sortOrder: 2 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'PRODUCTS', pricingType: 'INCLUDED', sortOrder: 3 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'QUOTATIONS', pricingType: 'INCLUDED', sortOrder: 4 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'INVOICES', pricingType: 'INCLUDED', sortOrder: 5 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'PAYMENTS', pricingType: 'INCLUDED', sortOrder: 6 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'WHATSAPP', pricingType: 'ADDON', addonPrice: 499, sortOrder: 7 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'TASKS', pricingType: 'INCLUDED', sortOrder: 8 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'REPORTS', pricingType: 'INCLUDED', sortOrder: 9 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'MARKETPLACE', pricingType: 'PER_USAGE', sortOrder: 10 },
    { packageCode: 'PROFESSIONAL', moduleCode: 'INVENTORY', pricingType: 'INCLUDED', sortOrder: 11 },

    // ── Enterprise ──
    { packageCode: 'ENTERPRISE', moduleCode: 'CONTACTS', pricingType: 'INCLUDED', sortOrder: 1 },
    { packageCode: 'ENTERPRISE', moduleCode: 'LEADS', pricingType: 'INCLUDED', sortOrder: 2 },
    { packageCode: 'ENTERPRISE', moduleCode: 'PRODUCTS', pricingType: 'INCLUDED', sortOrder: 3 },
    { packageCode: 'ENTERPRISE', moduleCode: 'QUOTATIONS', pricingType: 'INCLUDED', sortOrder: 4 },
    { packageCode: 'ENTERPRISE', moduleCode: 'INVOICES', pricingType: 'INCLUDED', sortOrder: 5 },
    { packageCode: 'ENTERPRISE', moduleCode: 'PAYMENTS', pricingType: 'INCLUDED', sortOrder: 6 },
    { packageCode: 'ENTERPRISE', moduleCode: 'WHATSAPP', pricingType: 'INCLUDED', sortOrder: 7 },
    { packageCode: 'ENTERPRISE', moduleCode: 'TASKS', pricingType: 'INCLUDED', sortOrder: 8 },
    { packageCode: 'ENTERPRISE', moduleCode: 'REPORTS', pricingType: 'INCLUDED', sortOrder: 9 },
    { packageCode: 'ENTERPRISE', moduleCode: 'MARKETPLACE', pricingType: 'INCLUDED', sortOrder: 10 },
    { packageCode: 'ENTERPRISE', moduleCode: 'INVENTORY', pricingType: 'INCLUDED', sortOrder: 11 },
  ];

  let linkCount = 0;
  for (const link of packageModuleLinks) {
    const packageId = packageMap[link.packageCode];
    const moduleId = moduleMap[link.moduleCode];

    if (!packageId || !moduleId) {
      console.warn(`  SKIP: package=${link.packageCode} or module=${link.moduleCode} not found`);
      continue;
    }

    console.log(`  Linking ${link.packageCode} → ${link.moduleCode} (${link.pricingType})`);
    await prisma.packageModule.upsert({
      where: {
        packageId_moduleId: { packageId, moduleId },
      },
      update: {
        pricingType: link.pricingType,
        addonPrice: link.addonPrice ?? null,
        disabledFeatures: link.disabledFeatures ?? [],
        sortOrder: link.sortOrder,
      },
      create: {
        packageId,
        moduleId,
        pricingType: link.pricingType,
        addonPrice: link.addonPrice ?? null,
        disabledFeatures: link.disabledFeatures ?? [],
        sortOrder: link.sortOrder,
      },
    });
    linkCount++;
  }

  console.log(`  Linked ${linkCount} package-module pairs.`);
  console.log('--- Modules & Packages seeding complete ---');
}
