export class CreateTaskCommand {
  constructor(
    public readonly title: string,
    public readonly createdById: string,
    public readonly creatorRoleLevel: number,
    public readonly tenantId: string,
    public readonly assignedToId?: string,
    public readonly description?: string,
    public readonly type?: string,
    public readonly customTaskType?: string,
    public readonly priority?: string,
    public readonly assignmentScope?: string,
    public readonly assignedDepartmentId?: string,
    public readonly assignedDesignationId?: string,
    public readonly assignedRoleId?: string,
    public readonly dueDate?: Date,
    public readonly dueTime?: string,
    public readonly startDate?: Date,
    public readonly recurrence?: string,
    public readonly recurrenceConfig?: Record<string, unknown>,
    public readonly parentTaskId?: string,
    public readonly entityType?: string,
    public readonly entityId?: string,
    public readonly tags?: string[],
    public readonly attachments?: Record<string, unknown>[],
    public readonly customFields?: Record<string, unknown>,
    public readonly estimatedMinutes?: number,
    public readonly reminderMinutesBefore?: number,
    public readonly activityType?: string,
    public readonly leadId?: string,
  ) {}
}
