/**
 * Seed data for 15 business types.
 * Each entry includes:
 *   - typeCode / typeName / industryCategory / description / icon / colorTheme
 *   - terminologyMap: key → label overrides (e.g. "Product" → "Service")
 *   - defaultModules / recommendedModules / excludedModules
 *   - dashboardWidgets / workflowTemplates
 */
export const BUSINESS_TYPE_SEED_DATA = [
  {
    typeCode: 'GENERAL_TRADING',
    typeName: 'General Trading',
    industryCategory: 'RETAIL',
    description: 'Buy and sell goods — retail / wholesale / distribution',
    icon: 'shopping-cart',
    colorTheme: '#3B82F6',
    terminologyMap: {},
    defaultModules: ['CONTACTS', 'ORGANIZATIONS', 'LEADS', 'PRODUCTS', 'QUOTATIONS', 'INVOICING'],
    recommendedModules: ['WHATSAPP', 'BULK_IMPORT', 'REPORTS'],
    excludedModules: [],
    dashboardWidgets: ['revenue_chart', 'lead_funnel', 'top_products', 'recent_activities'],
    workflowTemplates: ['lead_to_quote', 'quote_to_invoice'],
  },
  {
    typeCode: 'IT_SERVICES',
    typeName: 'IT / Software Services',
    industryCategory: 'SERVICES',
    description: 'Software development, IT consulting, SaaS',
    icon: 'monitor',
    colorTheme: '#6366F1',
    terminologyMap: { Product: 'Service', Quotation: 'Proposal', Invoice: 'Bill' },
    defaultModules: ['CONTACTS', 'ORGANIZATIONS', 'LEADS', 'QUOTATIONS', 'INVOICING', 'TASKS'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'WORKFLOWS', 'REPORTS'],
    excludedModules: [],
    dashboardWidgets: ['revenue_chart', 'project_status', 'lead_funnel', 'task_board'],
    workflowTemplates: ['lead_to_proposal', 'proposal_to_project'],
  },
  {
    typeCode: 'MANUFACTURING',
    typeName: 'Manufacturing',
    industryCategory: 'MANUFACTURING',
    description: 'Production, assembly, and distribution of goods',
    icon: 'factory',
    colorTheme: '#F59E0B',
    terminologyMap: { Product: 'Finished Good', Lead: 'Inquiry', Organization: 'Buyer' },
    defaultModules: ['CONTACTS', 'ORGANIZATIONS', 'LEADS', 'PRODUCTS', 'QUOTATIONS', 'INVOICING'],
    recommendedModules: ['BULK_IMPORT', 'REPORTS', 'WORKFLOWS'],
    excludedModules: [],
    dashboardWidgets: ['production_overview', 'order_pipeline', 'revenue_chart', 'top_products'],
    workflowTemplates: ['inquiry_to_order', 'order_to_dispatch'],
  },
  {
    typeCode: 'REAL_ESTATE',
    typeName: 'Real Estate',
    industryCategory: 'REAL_ESTATE',
    description: 'Property sales, rentals, brokerage',
    icon: 'building-2',
    colorTheme: '#10B981',
    terminologyMap: { Product: 'Property', Lead: 'Prospect', Quotation: 'Offer', Organization: 'Builder / Owner' },
    defaultModules: ['CONTACTS', 'LEADS', 'ACTIVITIES', 'FOLLOW_UPS', 'TOUR_PLANS'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'REPORTS'],
    excludedModules: ['PRODUCTS'],
    dashboardWidgets: ['property_listings', 'lead_funnel', 'site_visits', 'revenue_chart'],
    workflowTemplates: ['prospect_to_visit', 'visit_to_booking'],
  },
  {
    typeCode: 'HEALTHCARE_CLINIC',
    typeName: 'Healthcare / Clinic',
    industryCategory: 'HEALTHCARE',
    description: 'Clinics, hospitals, diagnostic centres',
    icon: 'heart-pulse',
    colorTheme: '#EF4444',
    terminologyMap: { Contact: 'Patient', Lead: 'Appointment', Organization: 'Referral', Product: 'Treatment' },
    defaultModules: ['CONTACTS', 'LEADS', 'ACTIVITIES', 'FOLLOW_UPS'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'REPORTS'],
    excludedModules: ['QUOTATIONS', 'PRODUCTS'],
    dashboardWidgets: ['appointments_today', 'patient_stats', 'follow_up_due', 'revenue_chart'],
    workflowTemplates: ['appointment_reminder', 'follow_up_after_visit'],
  },
  {
    typeCode: 'EDUCATION',
    typeName: 'Education / Coaching',
    industryCategory: 'EDUCATION',
    description: 'Schools, coaching centres, ed-tech',
    icon: 'graduation-cap',
    colorTheme: '#8B5CF6',
    terminologyMap: { Contact: 'Student', Lead: 'Enquiry', Organization: 'Institute', Product: 'Course' },
    defaultModules: ['CONTACTS', 'LEADS', 'ACTIVITIES', 'FOLLOW_UPS'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'BULK_IMPORT'],
    excludedModules: ['QUOTATIONS'],
    dashboardWidgets: ['enrollment_funnel', 'batch_overview', 'fee_collection', 'recent_enquiries'],
    workflowTemplates: ['enquiry_to_enrollment', 'fee_reminder'],
  },
  {
    typeCode: 'RESTAURANT_FOOD',
    typeName: 'Restaurant / Food & Beverage',
    industryCategory: 'FOOD_BEVERAGE',
    description: 'Restaurants, cafes, catering, cloud kitchens',
    icon: 'utensils',
    colorTheme: '#F97316',
    terminologyMap: { Product: 'Menu Item', Lead: 'Reservation', Contact: 'Customer', Organization: 'Vendor' },
    defaultModules: ['CONTACTS', 'PRODUCTS', 'INVOICING'],
    recommendedModules: ['WHATSAPP', 'REPORTS'],
    excludedModules: ['LEADS', 'QUOTATIONS', 'TOUR_PLANS'],
    dashboardWidgets: ['daily_sales', 'top_items', 'customer_count', 'revenue_chart'],
    workflowTemplates: ['order_to_delivery'],
  },
  {
    typeCode: 'ECOMMERCE',
    typeName: 'E-Commerce',
    industryCategory: 'ECOMMERCE',
    description: 'Online stores, D2C brands, marketplace sellers',
    icon: 'globe',
    colorTheme: '#06B6D4',
    terminologyMap: { Lead: 'Cart Abandonment', Quotation: 'Order' },
    defaultModules: ['CONTACTS', 'PRODUCTS', 'INVOICING', 'LEADS'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'BULK_IMPORT', 'REPORTS'],
    excludedModules: ['TOUR_PLANS'],
    dashboardWidgets: ['order_pipeline', 'revenue_chart', 'top_products', 'customer_stats'],
    workflowTemplates: ['cart_recovery', 'order_confirmation'],
  },
  {
    typeCode: 'CONSULTING',
    typeName: 'Consulting / Professional Services',
    industryCategory: 'SERVICES',
    description: 'Management consulting, legal, CA firms',
    icon: 'briefcase',
    colorTheme: '#64748B',
    terminologyMap: { Product: 'Service', Quotation: 'Proposal', Lead: 'Opportunity' },
    defaultModules: ['CONTACTS', 'ORGANIZATIONS', 'LEADS', 'QUOTATIONS', 'INVOICING', 'TASKS'],
    recommendedModules: ['EMAIL', 'REPORTS', 'WORKFLOWS'],
    excludedModules: [],
    dashboardWidgets: ['pipeline_value', 'lead_funnel', 'task_board', 'revenue_chart'],
    workflowTemplates: ['opportunity_to_proposal', 'engagement_lifecycle'],
  },
  {
    typeCode: 'CONSTRUCTION',
    typeName: 'Construction / Infrastructure',
    industryCategory: 'CONSTRUCTION',
    description: 'Builders, contractors, civil engineering',
    icon: 'hard-hat',
    colorTheme: '#D97706',
    terminologyMap: { Product: 'Material', Lead: 'Project Inquiry', Organization: 'Contractor', Quotation: 'Estimate' },
    defaultModules: ['CONTACTS', 'ORGANIZATIONS', 'LEADS', 'QUOTATIONS', 'INVOICING'],
    recommendedModules: ['TASKS', 'REPORTS', 'DOCUMENTS'],
    excludedModules: [],
    dashboardWidgets: ['project_pipeline', 'material_tracker', 'revenue_chart', 'lead_funnel'],
    workflowTemplates: ['inquiry_to_estimate', 'project_lifecycle'],
  },
  {
    typeCode: 'TRAVEL_TOURISM',
    typeName: 'Travel & Tourism',
    industryCategory: 'TRAVEL',
    description: 'Travel agencies, tour operators, hospitality',
    icon: 'plane',
    colorTheme: '#0EA5E9',
    terminologyMap: { Product: 'Package', Lead: 'Booking Inquiry', Quotation: 'Itinerary', Contact: 'Traveller' },
    defaultModules: ['CONTACTS', 'LEADS', 'QUOTATIONS', 'INVOICING', 'FOLLOW_UPS'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'REPORTS'],
    excludedModules: ['PRODUCTS'],
    dashboardWidgets: ['booking_pipeline', 'upcoming_trips', 'revenue_chart', 'customer_stats'],
    workflowTemplates: ['inquiry_to_booking', 'pre_trip_reminder'],
  },
  {
    typeCode: 'AUTOMOTIVE',
    typeName: 'Automotive / Dealership',
    industryCategory: 'AUTOMOTIVE',
    description: 'Car/bike dealerships, auto parts, servicing',
    icon: 'car',
    colorTheme: '#1E40AF',
    terminologyMap: { Product: 'Vehicle', Lead: 'Walk-in', Quotation: 'Price Quote', Contact: 'Buyer' },
    defaultModules: ['CONTACTS', 'LEADS', 'PRODUCTS', 'QUOTATIONS', 'INVOICING', 'FOLLOW_UPS'],
    recommendedModules: ['WHATSAPP', 'REPORTS'],
    excludedModules: [],
    dashboardWidgets: ['inventory_status', 'lead_funnel', 'test_drive_schedule', 'revenue_chart'],
    workflowTemplates: ['walkin_to_testdrive', 'testdrive_to_booking'],
  },
  {
    typeCode: 'EVENT_MANAGEMENT',
    typeName: 'Event Management',
    industryCategory: 'EVENTS',
    description: 'Event planners, wedding planners, exhibitions',
    icon: 'calendar-days',
    colorTheme: '#EC4899',
    terminologyMap: { Product: 'Service Package', Lead: 'Event Inquiry', Quotation: 'Proposal', Organization: 'Venue' },
    defaultModules: ['CONTACTS', 'LEADS', 'QUOTATIONS', 'INVOICING', 'ACTIVITIES'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'TASKS', 'REPORTS'],
    excludedModules: [],
    dashboardWidgets: ['upcoming_events', 'lead_funnel', 'revenue_chart', 'task_board'],
    workflowTemplates: ['inquiry_to_proposal', 'event_execution'],
  },
  {
    typeCode: 'FINANCIAL_SERVICES',
    typeName: 'Financial Services / Insurance',
    industryCategory: 'FINANCE',
    description: 'Banks, NBFCs, insurance brokers, mutual funds',
    icon: 'landmark',
    colorTheme: '#059669',
    terminologyMap: { Product: 'Policy / Scheme', Lead: 'Application', Quotation: 'Premium Quote', Contact: 'Client' },
    defaultModules: ['CONTACTS', 'ORGANIZATIONS', 'LEADS', 'QUOTATIONS', 'FOLLOW_UPS'],
    recommendedModules: ['WHATSAPP', 'EMAIL', 'REPORTS', 'WORKFLOWS'],
    excludedModules: ['PRODUCTS'],
    dashboardWidgets: ['application_pipeline', 'policy_renewals', 'revenue_chart', 'client_stats'],
    workflowTemplates: ['application_to_approval', 'renewal_reminder'],
  },
  {
    typeCode: 'LAUNDRY_SERVICES',
    typeName: 'Laundry / Dry Cleaning',
    industryCategory: 'SERVICES',
    description: 'Laundry shops, dry cleaners, press services',
    icon: 'shirt',
    colorTheme: '#7C3AED',
    terminologyMap: { Product: 'Service', Lead: 'Order', Contact: 'Customer', Quotation: 'Rate Card' },
    defaultModules: ['CONTACTS', 'INVOICING'],
    recommendedModules: ['WHATSAPP', 'REPORTS'],
    excludedModules: ['LEADS', 'QUOTATIONS', 'PRODUCTS', 'TOUR_PLANS', 'ORGANIZATIONS'],
    dashboardWidgets: ['daily_orders', 'revenue_chart', 'customer_stats', 'pending_pickups'],
    workflowTemplates: ['order_to_delivery'],
  },
];
