#!/usr/bin/env bash
# help-generator.sh — Generate .claude/HELP.md for CRMSoft
# Usage: bash scripts/skills/help-generator.sh

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HELP_FILE="$REPO_ROOT/.claude/HELP.md"
DATE=$(date +%Y-%m-%d)

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  CRMSoft Help Generator (PM CLI Phase 2)                 ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo "  Generating: .claude/HELP.md"

cat > "$HELP_FILE" << 'HELPEOF'
# CRMSoft Developer Help

> Generated by PM CLI Phase 2 Help Skill
> Run `pnpm help:generate` to refresh

---

## Login Credentials (Demo/Dev)

| Portal | URL | Email | Password |
|--------|-----|-------|----------|
| CRM Admin | http://localhost:3005 | admin@crm.com | Admin@123 |
| Vendor Panel | http://localhost:3006 | vendor@crm.com | Vendor@123 |
| Customer Portal | http://localhost:3007 | customer@crm.com | Customer@123 |
| Marketplace | http://localhost:3008 | market@crm.com | Market@123 |
| WL Admin | http://localhost:3009 | wladmin@crm.com | WLAdmin@123 |
| WL Partner | http://localhost:3011 | partner@crm.com | Partner@123 |
| Platform Console | http://localhost:3012 | console@crm.com | Console@123 |

> **Note:** These are seeded demo credentials. Check `Application/backend/prisma/*/seed.ts` for latest.

---

## Portal URLs

| Portal | Port | Command |
|--------|------|---------|
| NestJS API | 3001 | `pnpm dev:api` |
| CRM Admin | 3005 | `pnpm dev:admin` |
| Vendor Panel | 3006 | `pnpm dev:vendor` |
| Customer Portal | 3007 | `pnpm dev:portal` |
| Marketplace | 3008 | `pnpm dev:marketplace` |
| WL Admin | 3009 | `pnpm dev:wl-admin` |
| WL API | 3010 | `pnpm dev:wl-api` |
| WL Partner | 3011 | `pnpm dev:wl-partner` |
| Platform Console | 3012 | `pnpm dev:platform-console` |

---

## Database Connections (Railway CRM_V1)

| DB | Purpose | Env Var |
|----|---------|---------|
| IdentityDB | Users, roles, permissions | `IDENTITY_DATABASE_URL` |
| PlatformDB | Modules, menus, config | `PLATFORM_DATABASE_URL` |
| WorkingDB | Leads, contacts, orders | `WORKING_DATABASE_URL` |
| MarketplaceDB | Offers, profiles, feed | `MARKETPLACE_DATABASE_URL` |
| PlatformConsoleDB | Admin console | `PLATFORM_CONSOLE_DATABASE_URL` |
| GlobalReferenceDB | Shared reference data | `GLOBAL_REFERENCE_DATABASE_URL` |
| DemoDB | Demo tenant data | `DEMO_DATABASE_URL` |

Host: `nozomi.proxy.rlwy.net:35324`

---

## Available Commands

### Dev Servers
```bash
pnpm dev              # all 9 portals
pnpm dev:crm          # API + CRM Admin + Vendor + Portal only
pnpm dev:wl           # WhiteLabel servers only
pnpm dev:api          # API only
pnpm kill             # kill all ports
```

### Build
```bash
pnpm build:api
pnpm build:admin
pnpm build:vendor
pnpm build:wl-api
pnpm build:wl-admin
pnpm build:wl-partner
pnpm build:platform-console
```

### Quality Gates
```bash
pnpm typecheck           # TypeScript check (Application/backend)
pnpm lint:prisma         # Prisma structure lint (7 rules)
pnpm audit:db            # DB Schema Auditor (3 checks, 19 module codes)
pnpm guard               # Architecture guard
pnpm health              # Full weekly health check
```

### Work Lifecycle (PM CLI)
```bash
pnpm work:start              # git pull + dep check + session log
pnpm work:close              # git commit + push + backup
pnpm work:status             # dashboard (branch, files, prompts)
pnpm work:pickup             # execute next planned prompt
pnpm work:pickup:batch       # execute all planned prompts
pnpm work:shell:start        # shell version of work:start
pnpm work:shell:close        # shell version of work:close
pnpm work:shell:status       # shell version of work:status
```

### Backup
```bash
pnpm backup              # create timestamped backup → .claude/backups/
pnpm backup:list         # list all backups
```

### Railway
```bash
pnpm railway:status      # Railway project status
pnpm railway:deploy      # Deploy to Railway
pnpm railway:logs        # Stream Railway logs
pnpm railway:restart     # Restart Railway service
pnpm railway:env:sync    # Pull Railway env vars locally
pnpm railway:env:pull    # View Railway env vars
```

### Skills (PM CLI Phase 2)
```bash
# Security
pnpm security                  # full 10-point audit
pnpm security:secrets          # secret scan only
pnpm security:deps             # CVE check
pnpm security:env              # .env exposure check
pnpm security:auth             # auth guard coverage

# Testing
pnpm test:generate             # scaffold missing test files
pnpm test:audit                # coverage gap report
pnpm test:fix                  # fix common test issues
pnpm test:api                  # run backend tests

# Changelog
pnpm changelog                 # generate since last tag
pnpm changelog:preview         # dry run preview

# Performance
pnpm perf                      # full audit
pnpm perf:bundle               # bundle sizes
pnpm perf:build                # build time tracking
pnpm perf:tests                # slow test detection
pnpm perf:api                  # API benchmarks

# i18n (Indian market)
pnpm i18n:scan                 # find hardcoded strings
pnpm i18n:missing              # missing translation keys
pnpm i18n:rtl                  # RTL compliance
pnpm i18n:extract              # sample strings

# Cost
pnpm cost                      # Railway + R2 analysis
pnpm cost:compare "hosting"    # compare providers
pnpm cost:forecast --users=10000  # scale estimate

# Help
pnpm help                      # this file
pnpm help:credentials          # login credentials
pnpm help:generate             # regenerate this file
pnpm whoami:git                # git identity + remote
```

---

## Installed Skills

| Skill | Script | Claude Skill |
|-------|--------|-------------|
| Security Audit | `scripts/skills/security.sh` | `.claude/skills/security/SKILL.md` |
| Test Generator | `scripts/skills/test-generator.sh` | `.claude/skills/test-generator/SKILL.md` |
| Changelog | `scripts/skills/changelog.sh` | `.claude/skills/changelog/SKILL.md` |
| Performance | `scripts/skills/performance.sh` | `.claude/skills/performance/SKILL.md` |
| i18n Gap Finder | `scripts/skills/i18n.sh` | `.claude/skills/i18n/SKILL.md` |
| Cost Optimizer | `scripts/skills/cost.sh` | `.claude/skills/cost/SKILL.md` |
| Help Generator | `scripts/skills/help-generator.sh` | — |

---

## Golden Rules (Quick Reference)

1. **Discovery-first** — check exist → update; not exist → create. Zero duplicacy
2. **Backend + Frontend together** — every feature has API + UI in one prompt
3. **CQRS+DDD pattern** — commands/, queries/, handlers/, domain/, presentation/
4. **AIC shared controls only** — AICTable, AICDrawer, AICToolbar. No exceptions
5. **API UX pattern** — loading skeleton → disable button on submit → toast on error/success
6. **Tenant isolation** — all queries filter by tenantId
7. **Production-safe** — backup before migration, rollback plan required
8. **Version-based changes** — v1 → v2 → v3, never delete old directly
9. **Module → Menu first** — new module needs menu entry before it works
10. **Audit everything** — every action logged

---

## 19 Locked Module Codes

`usr cfg inv crm sal pay acc tax hr mkt lic ven wf not rpt doc cmn aud qa`

Enforced by: `pnpm audit:db` + CI gate

---

## Vertical Prefixes (7 locked)

| Prefix | Vertical |
|--------|---------|
| `gv_` | General/Generic |
| `ph_` | Pharma |
| `re_` | Real Estate |
| `ag_` | Agriculture |
| `ed_` | Education |
| `mf_` | Manufacturing |
| `rt_` | Retail |

---

## Troubleshooting

### API won't start
```bash
pnpm kill                     # kill port conflicts
cd Application/backend && pnpm typecheck   # check TS errors
```

### DB connection failed
```bash
cat Application/backend/.env | grep DATABASE_URL   # verify URLs
railway status                # check Railway services
```

### Audit:db failing
```bash
cd Application/backend && pnpm audit:db    # run directly for full output
# Check: 19 module codes, vertical prefixes, cross-DB includes
```

### Prisma client not generated
```bash
cd Application/backend && pnpm prisma:generate:all
```

### Husky hooks failing
```bash
echo "feat(test): message" | npx commitlint   # test commitlint
bash scripts/architecture-guard.sh            # test guard
```

---

## File Structure Reference

```
CRM-SOFT/
├── Application/backend/src/
│   ├── modules/core/          ← common modules (auth, prisma, permissions)
│   ├── modules/customer/      ← CRM features (leads, contacts)
│   ├── modules/softwarevendor/ ← Admin Console
│   ├── modules/marketplace/   ← MarketHub
│   ├── modules/vertical/      ← trade-specific extensions
│   └── modules/plugins/       ← integrations (WhatsApp, Razorpay)
├── Customer/frontend/crm-admin/src/
├── Vendor/frontend/vendor-panel/src/
├── .claude/
│   ├── CLAUDE.md              ← project rules (DO NOT EDIT)
│   ├── config.json            ← PM CLI config
│   ├── skills/                ← skill SKILL.md files
│   ├── working/               ← prompt pipeline (planned/in-progress/completed)
│   └── context/               ← local context files
├── scripts/
│   ├── architecture-guard.sh  ← DO NOT MODIFY
│   ├── lib/                   ← zero-risk wrapper + helpers
│   ├── skills/                ← PM CLI skill scripts
│   └── work/                  ← work lifecycle scripts
└── docs/
    ├── health-reports/        ← weekly health check outputs
    ├── security/              ← security audit reports
    ├── testing/               ← coverage gap reports
    ├── performance/           ← perf reports
    ├── i18n/                  ← i18n gap reports
    └── costs/                 ← cost analysis reports
```

HELPEOF

echo "  ✅ Generated: .claude/HELP.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Run: pnpm help  (after adding script to package.json)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
