/**
 * TENANT_SCOPED_MODELS — Prisma model names (PascalCase) with a tenantId field
 * in the working DB schema.
 *
 * This is a DOCUMENTATION set only. At runtime, the $extends factory in
 * tenant-aware-prisma.ts uses $allModels (covers every model), so this list
 * does not gate any query. Its purpose is:
 *   1. Auditor reference — compare against schema changes at release time
 *   2. Fast-path for any future per-model logic
 *
 * AUDIT: 2026-04-27 (M8a Phase 2)
 *   Source: grep tenantId from apps-backend/api/prisma/working/v1/*.prisma
 *   Total:  220 models (of 228 in working schema)
 *   Missing tenantId: AMCPlanTemplate*, ControlRoomRule*, CronJobConfig*,
 *                     InventoryLabel*, PriceListItem*, RateLimitTier*,
 *                     ServiceRate*, TaskWatcher* (config/meta tables)
 *                     (* not in this set)
 */
export const TENANT_SCOPED_MODELS = new Set([
  // ── CRM ──────────────────────────────────────────────────────────────────
  'Activity',
  'AMCContract',
  'AMCSchedule',
  'AssignmentRule',
  'CalendarEvent',
  'Comment',
  'Communication',
  'Contact',
  'ContactFilter',
  'ContactOrganization',
  'Demo',
  'EntityOwner',
  'EntityVerificationRecord',
  'EscalationRule',
  'EventHistory',
  'EventParticipant',
  'FollowUp',
  'Lead',
  'LeadFilter',
  'Manufacturer',
  'ManufacturerContact',
  'ManufacturerOrganization',
  'Organization',
  'OrganizationFilter',
  'OrganizationLocation',
  'OwnershipLog',
  'RawContact',
  'RawContactFilter',
  'RecurringEvent',
  'Reminder',
  'ScheduledEvent',
  'ServiceCharge',
  'ServiceVisitLog',
  'SupportTicket',
  'Task',
  'TaskHistory',
  'TaskLogicConfig',
  'TourPlan',
  'TourPlanPhoto',
  'TourPlanVisit',
  'WarrantyClaim',
  'WarrantyRecord',
  'WarrantyTemplate',

  // ── Sales ─────────────────────────────────────────────────────────────────
  'DeliveryChallan',
  'DeliveryChallanItem',
  'PriceList',
  'Quotation',
  'QuotationActivity',
  'QuotationComparison',
  'QuotationLineItem',
  'QuotationNegotiationLog',
  'QuotationSendLog',
  'QuotationTemplate',
  'SaleMaster',
  'SaleOrder',
  'SaleOrderItem',
  'SaleReturn',
  'SaleReturnItem',
  'SalesTarget',

  // ── Inventory ─────────────────────────────────────────────────────────────
  'BOMFormula',
  'BOMFormulaItem',
  'BOMProduction',
  'CustomerGroupMapping',
  'CustomerPriceGroup',
  'GoodsReceipt',
  'GoodsReceiptItem',
  'InventoryItem',
  'Product',
  'ProductFilter',
  'ProductPrice',
  'ProductRelation',
  'ProductTaxDetail',
  'ProductUnitConversion',
  'PurchaseMaster',
  'PurchaseOrder',
  'PurchaseOrderItem',
  'PurchaseQuotation',
  'PurchaseQuotationItem',
  'PurchaseRFQ',
  'PurchaseRFQItem',
  'ScrapRecord',
  'SerialMaster',
  'StockAdjustment',
  'StockLocation',
  'StockSummary',
  'StockTransaction',
  'UnitConversion',
  'UnitMaster',

  // ── Accounting ────────────────────────────────────────────────────────────
  'AccountGroup',
  'AccountTransaction',
  'BankAccount',
  'BankReconciliation',
  'CreditNote',
  'DebitNote',
  'DebitNoteItem',
  'GSTReturn',
  'GstVerificationLog',
  'Invoice',
  'InvoiceLineItem',
  'LedgerMapping',
  'LedgerMaster',
  'ProformaInvoice',
  'ProformaLineItem',
  'PurchaseInvoice',
  'PurchaseInvoiceItem',
  'SavedFormula',
  'TDSRecord',

  // ── Payments ──────────────────────────────────────────────────────────────
  'Payment',
  'PaymentReceipt',
  'PaymentRecord',
  'PaymentReminder',
  'Refund',

  // ── Communication ─────────────────────────────────────────────────────────
  'CampaignRecipient',
  'CommunicationLog',
  'Email',
  'EmailAccount',
  'EmailAttachment',
  'EmailCampaign',
  'EmailFooterTemplate',
  'EmailSignature',
  'EmailTemplate',
  'EmailThread',
  'EmailTrackingEvent',
  'EmailUnsubscribe',
  'WaBroadcast',
  'WaBroadcastRecipient',
  'WaChatbotFlow',
  'WaConversation',
  'WaMessage',
  'WaOptOut',
  'WaQuickReply',
  'WaTemplate',
  'WhatsAppBusinessAccount',
  'WebhookDelivery',
  'WebhookEndpoint',

  // ── Notifications ─────────────────────────────────────────────────────────
  'Notification',
  'NotificationConfig',
  'NotificationPreference',
  'NotificationTemplate',
  'PushSubscription',

  // ── Documents ─────────────────────────────────────────────────────────────
  'CloudConnection',
  'Document',
  'DocumentActivity',
  'DocumentAttachment',
  'DocumentFolder',
  'DocumentShareLink',
  'DocumentTemplate',
  'ExportJob',
  'ImportJob',
  'ImportProfile',
  'ImportRow',
  'TenantTemplateCustomization',

  // ── Reports ───────────────────────────────────────────────────────────────
  'ReportBookmark',
  'ReportDefinition',
  'ReportExportLog',
  'ReportTemplate',
  'ScheduledReport',

  // ── Workflows & Approvals ─────────────────────────────────────────────────
  'ApprovalRequest',
  'ApprovalRule',
  'Workflow',
  'WorkflowActionLog',
  'WorkflowApproval',
  'WorkflowHistory',
  'WorkflowInstance',
  'WorkflowSlaEscalation',
  'WorkflowState',
  'WorkflowTransition',

  // ── Config (tenant-specific) ──────────────────────────────────────────────
  'ApiKey',
  'ApiRequestLog',
  'AutoNumberSequence',
  'BlockedSlot',
  'Brand',
  'BrandContact',
  'BrandOrganization',
  'BusinessHoursSchedule',
  'BusinessLocation',
  'CalendarConfig',
  'CalendarHighlight',
  'CompanyCity',
  'CompanyCountry',
  'CompanyPincode',
  'CompanyProfile',
  'CompanyState',
  'ControlRoomAuditLog',
  'ControlRoomDraft',
  'ControlRoomValue',
  'CronJobRunLog',
  'CustomFieldDefinition',
  'DataMaskingPolicy',
  'EntityConfigValue',
  'GoogleConnection',
  'HolidayCalendar',
  'NotionConfig',
  'QuietHourConfig',
  'SavedFilter',
  'ShortcutDefinition',
  'ShortcutUserOverride',
  'TableConfig',
  'TenantRuleCacheVersion',

  // ── Audit Logs ────────────────────────────────────────────────────────────
  'SyncAuditLog',
  'SyncChangeLog',
  'SyncConflict',
  'SyncDevice',
  'SyncFlushCommand',
  'SyncPolicy',
  'SyncWarningRule',
  'UnmaskAuditLog',

  // ── AI ────────────────────────────────────────────────────────────────────
  'AiChatMessage',
  'AiChatSession',
  'AiDataset',
  'AiDocument',
  'AiEmbedding',
  'AiModel',
  'AiSettings',
  'AiSystemPrompt',
  'AiTrainingJob',
  'AiUsageLog',

  // ── Calendar / Availability ───────────────────────────────────────────────
  'UserAvailability',
  'UserCalendarSync',
]);

/**
 * Models that are accessed cross-tenant or have no tenantId.
 * All live in platform/identity DBs — not in working DB.
 * Working DB models without tenantId (meta/config tables):
 *   AMCPlanTemplate, ControlRoomRule, CronJobConfig, InventoryLabel,
 *   PriceListItem, RateLimitTier, ServiceRate, TaskWatcher
 */
export const TENANT_EXEMPT_MODELS = new Set([
  // Platform DB — global config
  'PageRegistry',
  'LookupValue',
  'LookupCategory',
  'SubscriptionPackage',
  'MarketplaceModule',
  'ModuleDefinition',
  'SoftwareOffer',
  // Identity DB — cross-tenant
  'Tenant',
  'Plan',
  'Subscription',
  'SuperAdmin',
  'Permission',
  'GlobalDefaultCredential',
]);
